import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import {mountBatchUI,batchUiSource} from '../.sites-runtime/batch-ui.mjs';import {batchRuntime as model} from '../.sites-runtime/batch.mjs';import {fixture} from './batch-fixtures.mjs';
class Node {constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.attrs={};this._text='';this.value='';this.disabled=false;this.checked=false;this.style={};}appendChild(child){this.children.push(child);return child;}replaceChildren(...children){this.children=children;this._text='';}setAttribute(k,v){this.attrs[k]=String(v);if(k==='xmlns')this.namespaceURI=v;}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(n=>n.textContent).join('');}}
const flush=()=>new Promise(r=>setTimeout(r,0));
function harness({serialized=false,failOnce=false}={}){const doc={createElement:tag=>new Node(tag,doc),createElementNS:(ns,tag)=>Object.assign(new Node(tag,doc),{namespaceURI:ns})};const root=new Node('div',doc),calls=[],draft={id:'draft-one',digest:'digest-one',requestKey:'original-key',batch:model.clean(fixture()),status:'pending',issues:[]};let locale='en',failed=false;const record={id:'saved-one',digest:'digest-one',batch:draft.batch,deleted_at:null,created_at:'2026-10-02T00:00:00Z'};let records=[];const options={model,window:{crypto:webcrypto,URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL(){}},confirm:()=>true},locale:()=>locale,namespace:()=> 'demo',prepare:async()=>{throw new Error('not used');},call:async(action,args)=>{calls.push({action,args:structuredClone(args)});if(action==='list'){if(args.batchId)return {record};return {batchRecords:records,batchDrafts:[draft],batchNextOffset:null};}if(action==='draft'){draft.batch=args.batch;draft.requestKey=args.requestKey;record.batch=args.batch;return {draft:{...draft},issues:[]};}if(action==='confirm'){records=[record];if(failOnce&&!failed){failed=true;throw new Error('timeout after commit');}return {record,deduplicated:failed};}return {};}};const mount=serialized?vm.runInNewContext(batchUiSource+';mountHealthBatchUI',{Intl,Map,Set,JSON,Object,Array,Number,Error}):mountBatchUI;const panel=mount(root,options);const walk=(node=root)=>[node,...node.children.flatMap(n=>walk(n))],buttons=key=>walk().filter(n=>n.tagName==='button'&&n.textContent===model.t(key,locale)),click=async key=>{const b=buttons(key)[0];assert.ok(b,'button '+key);assert.equal(b.disabled,false,key+' enabled');b.onclick();await flush();await flush();};return {root,panel,mount,calls,draft,record,options,walk,buttons,click,locale:value=>{locale=value;panel.paint();}};}
test('browser review creates draft only, explicit whole-batch save readbacks all sessions, bilingual repaint preserves input',async()=>{const h=harness({serialized:true});await flush();await h.click('reviewResults');assert.equal(h.walk().some(n=>n.type==='date'),false);await h.click('edit');assert.ok(h.walk().some(n=>n.value==='2026-10-01'));assert.ok(h.walk().some(n=>n.value==='2026-10-02'));h.locale('zh-Hant');assert.ok(h.root.textContent.includes('骨骼肌重量'));h.locale('en');await h.click('applyEdit');assert.equal(h.buttons('save')[0].disabled,false);await h.click('save');assert.deepEqual(h.calls.filter(c=>c.action==='confirm')[0].args,{draftId:'draft-one',expectedDigest:'digest-one',confirmed:true});assert.ok(h.calls.some(c=>c.action==='list'&&c.args.batchId==='saved-one'));assert.ok(h.root.textContent.includes('Saved and read back'));assert.ok(h.root.textContent.includes('30.2 kg'));h.panel.dispose();});
test('moving screenshot observation splits/merges without rewriting source ID/index; changed grouping cannot save',async()=>{const h=harness();await flush();await h.click('reviewResults');await h.click('edit');const labels=h.walk().filter(n=>n.tagName==='label'),move=labels.filter(l=>l.children[0]?.textContent===model.t('move','en')).map(l=>l.children.find(n=>n.tagName==='select')).find(n=>n.value==='morning');move.value='later-day';move.onchange();await flush();assert.equal(h.buttons('save').length,0);assert.ok(h.root.textContent.includes('image-fixture : 0'));await h.click('applyEdit');assert.equal(h.buttons('save')[0].disabled,true);assert.ok(h.root.textContent.includes('differs from the session'));assert.equal(h.calls.some(c=>c.action==='confirm'),false);h.panel.dispose();});
test('uncertain save keeps frozen request; reload replays exact guard and reads canonical result without duplicate',async()=>{const h=harness({failOnce:true});await flush();await h.click('reviewResults');await h.click('save');assert.ok(h.root.textContent.includes('Transport outcome is uncertain'));await h.click('cancel');assert.ok(h.root.textContent.includes('Closing cannot revoke'));await h.click('reload');const confirmations=h.calls.filter(c=>c.action==='confirm');assert.equal(confirmations.length,2);assert.deepEqual(confirmations[0].args,confirmations[1].args);assert.ok(h.root.textContent.includes('Saved and read back'));h.panel.dispose();});
test('custom labels are inserted as text, no executable HTML; no health data localStorage calls',async()=>{const h=harness();await flush();h.draft.batch.sessions[0].observations[0].label='<img src=x onerror=alert(1)>';h.draft.batch.sessions[0].observations[0].metric='custom:label';await h.click('reviewResults');await h.click('edit');assert.ok(h.walk().some(n=>n.tagName==='input'&&n.value.includes('<img src=')));assert.ok(!h.walk().some(n=>n.tagName==='img'));assert.ok(!batchUiSource.includes('localStorage'));h.panel.dispose();});
test('image/draft consents survive repaint and reach one batch analysis; selecting a new batch resets consent',async()=>{const h=harness();await flush();const prepared={key:'batch-'+'a'.repeat(64),duplicates:[],images:[{sourceHash:'1'.repeat(64),metadata:{status:'missing',exifDateTime:null,exifOffset:null},bytes:new Uint8Array([1])}]};const analyses=[];h.options.prepare=async()=>prepared;h.options.analyze=async(p,settings)=>{analyses.push({p,settings});};h.panel.paint();const choose=()=>{const picker=h.walk().find(n=>n.tagName==='input'&&n.type==='file');picker.files=[{type:'image/png',size:4}];picker.onchange();};choose();const check=key=>{const l=h.walk().find(n=>n.tagName==='label'&&n.children.some(c=>c.textContent===model.t(key,'en')));const box=l.children.find(c=>c.type==='checkbox');box.checked=true;box.onchange();};check('consent');await h.click('analyze');assert.equal(analyses.length,1);assert.equal(analyses[0].settings.allowDraft,true);assert.equal(analyses[0].settings.namespace,'demo');assert.equal(h.calls.some(c=>c.action==='confirm'),false);choose();assert.equal(h.buttons('analyze')[0].disabled,true);assert.equal(analyses.length,1);h.panel.dispose();});
test('upload-first empty and selected standalone states contain no manual or fake analysis controls',async()=>{const h=harness();await flush();for(const key of ['newSession','addMetric','draft','reading','save','edit','suggest'])assert.equal(h.buttons(key).length,0,key);assert.ok(h.root.textContent.includes('not connected'));assert.ok(h.walk().some(n=>n.tagName==='a'&&n.href==='https://chatgpt.com/'));const picker=h.walk().find(n=>n.type==='file');picker.files=[{type:'image/png',size:4}];picker.onchange();assert.equal(h.buttons('analyze').length,0);assert.equal(h.walk().some(n=>n.type==='date'),false);assert.equal(h.calls.some(c=>['draft','confirm'].includes(c.action)),false);h.panel.dispose();});
test('results open read-only, edits are optional and cancelling restores original values across locales',async()=>{const h=harness();await flush();await h.click('reviewResults');assert.equal(h.walk().some(n=>n.type==='number'),false);await h.click('edit');const value=h.walk().find(n=>n.type==='number');value.value='88';value.onchange();h.locale('zh-Hant');assert.ok(h.walk().some(n=>n.value==='88'));await h.click('cancelEdit');assert.ok(!h.root.textContent.includes('88 kg'));assert.ok(h.root.textContent.includes('72.4 kg'));h.locale('en');await h.click('cancel');assert.equal(h.buttons('edit').length,0);assert.equal(h.buttons('save').length,0);h.panel.dispose();});


const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
for(const serialized of [false,true]) test('disposed '+(serialized?'iframe':'website')+' panel cannot repaint replacement or act through retained handlers',async()=>{
 const h=harness({serialized});await flush();h.panel.dispose();const wait=deferred(),calls=[];
 const old=h.mount(h.root,{...h.options,namespace:()=> 'demo',trash:()=> false,call:(action,args)=>{calls.push({action,args});return wait.promise;}});
 const retained=h.walk().find(n=>n.tagName==='button'&&n.textContent===model.t('reload','en'));
 old.dispose();const replacement=h.mount(h.root,{...h.options,namespace:()=> 'real',trash:()=> true,call:async()=>({batchRecords:[],batchDrafts:[],batchNextOffset:null})});await flush();
 const children=[...h.root.children],text=h.root.textContent;
 wait.resolve({batchRecords:[],batchDrafts:[h.draft],batchNextOffset:null});await flush();await flush();
 old.paint();old.setData({batchRecords:[h.record],batchDrafts:[h.draft],batchNextOffset:null});old.receiveDraft(h.draft);await old.refresh();retained.onclick();old.dispose();
 assert.deepEqual(h.root.children,children);assert.equal(h.root.textContent,text);assert.equal(calls.length,1);assert.equal(calls[0].args.namespace,'demo');replacement.dispose();
});
test('disposing during confirmation prevents old-namespace readback and late success/error repaint',async()=>{
 for(const reject of [false,true]){const h=harness();await flush();await h.click('reviewResults');const wait=deferred(),original=h.options.call;
 h.options.call=(action,args)=>action==='confirm'?wait.promise:original(action,args);
 h.buttons('save')[0].onclick();await flush();h.panel.dispose();
 const replacement=h.mount(h.root,{...h.options,namespace:()=> 'real',call:async()=>({batchRecords:[],batchDrafts:[],batchNextOffset:null})});await flush();const children=[...h.root.children];
 if(reject)wait.reject(new Error('late transport failure'));else wait.resolve({record:h.record});await flush();await flush();
 assert.deepEqual(h.root.children,children);assert.equal(h.calls.some(c=>c.args.batchId),false);replacement.dispose();}
});
test('late preparation ignoring cancellation cannot mutate replacement or send analysis',async()=>{
 const h=harness();await flush();const wait=deferred();let analyzed=0,cancelled;
 h.options.prepare=(_files,check)=>{cancelled=check;return wait.promise;};h.options.analyze=async()=>{analyzed++;};h.panel.paint();
 const picker=h.walk().find(n=>n.type==='file');picker.files=[{type:'image/png',size:4}];picker.onchange();
 const consent=h.walk().find(n=>n.tagName==='label'&&n.children.some(c=>c.textContent===model.t('consent','en'))).children.find(n=>n.type==='checkbox');consent.checked=true;consent.onchange();
 h.buttons('analyze')[0].onclick();await flush();h.panel.dispose();assert.equal(cancelled(),true);
 h.root.textContent='replacement destination';wait.resolve({key:'synthetic-key',images:[],duplicates:[]});await flush();await flush();
 assert.equal(h.root.textContent,'replacement destination');assert.equal(analyzed,0);
});
test('scope changes invalidate pending work even before its panel is disposed',async()=>{
 const h=harness();await flush();h.panel.dispose();let namespace='demo',trash=false;const wait=deferred();
 const old=h.mount(h.root,{...h.options,namespace:()=>namespace,trash:()=>trash,call:()=>wait.promise});namespace='real';trash=true;h.root.textContent='new scope';
 wait.reject(new Error('late failure'));await flush();await flush();await old.refresh();old.paint();assert.equal(h.root.textContent,'new scope');old.dispose();
});
function chooseFiles(h){const picker=h.walk().find(n=>n.type==='file');picker.files=[{type:'image/png',size:4}];picker.onchange();}
function consentTo(h,key='byokConsent'){const label=h.walk().find(n=>n.tagName==='label'&&n.children.some(c=>c.textContent===model.t(key,'en')));const input=label.children.find(n=>n.type==='checkbox');input.checked=true;input.onchange();}
function fakeByok(h,reply){let key='',disposed=false;const analyses=[];h.options.byok={hasKey:()=>!!key,setKey:value=>key=value,clearKey:()=>key='',dispose:()=>{key='';disposed=true;},analyze:async(p,settings)=>{analyses.push({p,settings});return typeof reply==='function'?reply(p,settings):reply;}};h.options.prepare=async()=>({key:'batch-'+'a'.repeat(64),duplicates:[],images:[]});h.panel.paint();return {analyses,disposed:()=>disposed,key:()=>key};}
function setKey(h){const input=h.walk().find(n=>n.type==='password');input.value='SYNTHETIC-NOT-AN-API-KEY';input.oninput();}
test('BYOK upload flow requires key and explicit billing/risk consent; results appear without saving or pre-result editor',async()=>{const h=harness();await flush();const batch=fixture();batch.groupingConfirmed=false;batch.sources[0].capture.reviewed=false;batch.sessions.forEach(s=>s.confirmed=false);const byok=fakeByok(h,{version:1,batch});chooseFiles(h);assert.equal(h.buttons('analyze')[0].disabled,true);assert.equal(h.buttons('edit').length,0);assert.ok(h.root.textContent.includes('billed to your OpenAI account'));assert.ok(h.root.textContent.includes('page code/extensions'));assert.ok(h.root.textContent.includes('30 days'));setKey(h);assert.equal(h.buttons('analyze')[0].disabled,true);consentTo(h);assert.equal(h.walk().find(n=>n.type==='password').value,'');await h.click('analyze');assert.equal(byok.analyses.length,1);assert.ok(h.root.textContent.includes('results are ready'));assert.equal(h.buttons('edit').length,1);assert.equal(h.buttons('save')[0].disabled,false);assert.equal(h.buttons('newSession').length,0);assert.equal(h.calls.some(c=>['draft','confirm'].includes(c.action)),false);await h.click('save');assert.equal(h.calls.filter(c=>c.action==='draft').length,1);assert.equal(h.calls.filter(c=>c.action==='confirm').length,1);assert.ok(h.calls.some(c=>c.args.batchId==='saved-one'));assert.ok(h.root.textContent.includes('Saved and read back'));assert.equal(h.calls.some(c=>JSON.stringify(c.args).includes('SYNTHETIC-NOT-AN-API-KEY')),false);h.panel.dispose();assert.equal(byok.key(),'');assert.equal(byok.disposed(),true);});
test('BYOK ambiguous result blocks saving until edit correction; editing saves guarded draft internally with one visible save',async()=>{const h=harness();await flush();const batch=fixture();batch.sessions[0].timezone=null;fakeByok(h,{version:1,batch});chooseFiles(h);setKey(h);consentTo(h);await h.click('analyze');assert.equal(h.buttons('save')[0].disabled,true);await h.click('edit');const label=h.walk().find(n=>n.tagName==='label'&&n.children[0]?.textContent===model.t('zone','en'));const input=label.children.find(n=>n.tagName==='input');input.value='UTC+08:00';input.onchange();assert.equal(h.buttons('draft').length,0);await h.click('applyEdit');assert.equal(h.buttons('save')[0].disabled,false);await h.click('save');assert.ok(h.root.textContent.includes('Saved and read back'));h.panel.dispose();});
test('missing host transport remains pending and cannot open fake extracted results or save',async()=>{const h=harness();await flush();h.options.analyze=async()=>{throw new Error('transportMissing');};h.options.prepare=async()=>({key:'batch-'+'a'.repeat(64),duplicates:[],images:[]});h.panel.paint();chooseFiles(h);consentTo(h,'consent');await h.click('analyze');assert.ok(h.root.textContent.includes('no usable declared image transport'));assert.equal(h.buttons('save').length,0);assert.equal(h.buttons('edit').length,0);assert.equal(h.calls.some(c=>c.action==='confirm'),false);h.panel.dispose();});
test('BYOK failure preserves selected images; retry needs explicit possible-charge approval and no automatic submission',async()=>{const h=harness();await flush();const byok=fakeByok(h,()=>{throw new Error('analysisTimeout');});chooseFiles(h);setKey(h);consentTo(h);await h.click('analyze');assert.equal(byok.analyses.length,1);assert.equal(h.walk().filter(n=>n.tagName==='img').length,1);assert.equal(h.buttons('save').length,0);assert.ok(h.root.textContent.includes('provider may still process or bill'));h.options.window.confirm=()=>false;await h.click('retryAnalysis');assert.equal(byok.analyses.length,1);h.options.window.confirm=text=>{assert.ok(text.includes('already have been billed'));return true;};await h.click('retryAnalysis');assert.equal(byok.analyses.length,2);assert.equal(byok.analyses[1].settings.retry,true);h.panel.dispose();});
test('forgetting BYOK key removes analysis authorization without changing canonical reports',async()=>{const h=harness();await flush();const byok=fakeByok(h,{version:1,batch:fixture()});chooseFiles(h);setKey(h);consentTo(h);await h.click('forgetKey');assert.equal(byok.key(),'');assert.equal(h.buttons('analyze')[0].disabled,true);assert.equal(byok.analyses.length,0);h.panel.dispose();});
test('result correction uses previous digest guard and one save; failed canonical readback never claims success',async()=>{for(const mismatch of [false,true]){const h=harness();await flush();await h.click('reviewResults');await h.click('edit');const value=h.walk().find(n=>n.type==='number');value.value='73';value.onchange();await h.click('applyEdit');const call=h.options.call;h.options.call=async(action,args)=>{const result=await call(action,args);return mismatch&&action==='list'&&args.batchId?{record:{...h.record,digest:'other-digest'}}:result;};await h.click('save');const request=h.calls.find(c=>c.action==='draft');assert.equal(request.args.replacesDraftId,'draft-one');assert.equal(request.args.expectedDigest,'digest-one');assert.ok(request.args.requestKey.startsWith('original-key-'));assert.equal(h.calls.filter(c=>c.action==='confirm').length,1);assert.equal(h.root.textContent.includes('Saved and read back'),!mismatch);h.panel.dispose();}});
