import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {batchRuntime as m,batchSource} from '../.sites-runtime/batch.mjs';import {photoMetadataSource} from '../.sites-runtime/photo-metadata.mjs';import {fixture,source,observation} from './batch-fixtures.mjs';import {webcrypto} from 'node:crypto';
test('mixed-day screenshot maps one source to several sessions without mixing metrics',()=>{const b=m.clean(fixture());assert.deepEqual(m.issues(b),[]);assert.equal(b.sessions.length,2);assert.equal(m.consolidate(b.sessions.find(s=>s.id==='morning')).length,3);assert.equal(m.consolidate(b.sessions.find(s=>s.id==='later-day'))[0].value,72.1);const suggestions=m.suggest({...b,sessions:[{...b.sessions[0],observations:b.sessions.flatMap(s=>s.observations)}]});assert.equal(suggestions.sessions.length,2);assert.equal(suggestions.groupingConfirmed,false);});
test('same-day separate sessions remain distinct; retry order canonicalizes deterministically',()=>{const b=fixture();b.sessions[1].date='2026-10-01';b.sessions[1].observations[0].displayedDate='2026-10-01';assert.deepEqual(m.issues(m.clean(b)),[]);assert.equal(m.clean(b).sessions.length,2);const reverse=structuredClone(b);reverse.sessions.reverse();reverse.sessions[1].observations.reverse();assert.deepEqual(m.clean(b),m.clean(reverse));});
test('mass and percentage are distinct, conflicts never average and repeated readings consolidate provenance',()=>{const b=fixture(),s=b.sessions[0];s.observations.push(observation(4,'2026-10-01',{metric:'skeletal_muscle_percent',value:40,unit:'%'}),observation(5));assert.deepEqual(m.issues(m.clean(b)),[]);assert.equal(m.consolidate(s).find(x=>x.metric==='weight').duplicate,true);s.observations.push(observation(6,'2026-10-01',{value:80}));assert.ok(m.issues(m.clean(b)).includes('conflict'));s.observations.at(-1).selected=false;assert.ok(m.issues(m.clean(b)).includes('observation'));s.observations.at(-1).resolution='Explicitly excluded conflicting test reading';assert.deepEqual(m.issues(m.clean(b)),[]);s.observations.find(o=>o.metric==='skeletal_muscle_mass').unit='%';assert.ok(m.issues(m.clean(b)).includes('observation'));});
test('capture date is not screenshot measurement date; photos with date mismatch need resolution',()=>{const b=fixture();b.sources[0].capture={...source().capture,status:'available',exifDateTime:'2026:10:03 08:15:30',exifOffset:'+08:00',note:''};assert.deepEqual(m.issues(m.clean(b)),[]);b.sources[0].kind='photo';assert.ok(m.issues(m.clean(b)).includes('displayConflict'));for(const s of b.sessions)for(const o of s.observations)o.resolution='User confirmed historical measurement versus later capture';assert.deepEqual(m.issues(m.clean(b)),[]);});
test('missing zone, partial uncertainty and explicit capture review block whole batch',()=>{const b=fixture();b.sessions[1].timezone=null;assert.ok(m.issues(m.clean(b)).includes('measurement'));b.sessions[1].timezone='UTC+08:00';b.sources[0].capture.reviewed=false;assert.ok(m.issues(m.clean(b)).includes('sourceReview'));b.sources[0].capture.reviewed=true;b.sessions[1].observations[0].value=null;assert.ok(m.issues(m.clean(b)).includes('observation'));});
test('date-only stays date-only; ambiguous/nonexistent DST requires explicit offset',()=>{const b=fixture();assert.equal(m.clean(b).sessions[0].time,null);assert.deepEqual(m.localInstants('2026-03-08','02:30','America/New_York'),[]);assert.equal(m.localInstants('2026-11-01','01:30','America/New_York').length,2);b.sessions[0]={...b.sessions[0],date:'2026-11-01',time:'01:30',timezone:'America/New_York',precision:'minute'};for(const o of b.sessions[0].observations)o.displayedDate='2026-11-01';assert.ok(m.issues(m.clean(b)).includes('measurement'));b.sessions[0].timezone='UTC-04:00';assert.deepEqual(m.issues(m.clean(b)),[]);});
test('rejects duplicate observation IDs, unknown private fields, oversized input and unsafe labels as HTML',()=>{const b=fixture();b.sessions[1].observations[0].index=0;assert.ok(m.issues(m.clean(b)).includes('observation'));assert.throws(()=>m.clean({...fixture(),gps:'private'}),/schema/);assert.throws(()=>m.clean({...fixture(),sources:Array.from({length:9},(_,i)=>source('source-'+i))}),/bounds/);const c=fixture();c.sessions[0].observations[0].metric='custom:scale_metric';c.sessions[0].observations[0].label='<img src=x onerror=alert(1)>';assert.equal(m.clean(c).sessions.find(s=>s.id==='morning').observations[0].label,c.sessions[0].observations[0].label);});
test('trends keep same metric and unit separate and exclude deleted batches',()=>{const b=fixture(),a={id:'one',batch:m.clean(b),deleted_at:null},c=structuredClone(a);c.id='two';c.batch.sessions[0].observations[0].unit='lb';const groups=m.trends([a,c,{...a,id:'deleted',deleted_at:'2026-10-02'}]);assert.equal(groups.filter(g=>g.metric==='weight').length,2);assert.equal(groups.find(g=>g.metric==='skeletal_muscle_mass').points.length,2);assert.ok(groups.every(g=>g.points.every(p=>p.batchId!=='deleted')));});
test('serialized validation and bilingual dictionaries preserve browser/server parity',()=>{const ctx={Intl,Date,Map,Set,Error,Number,Object,JSON};vm.runInNewContext(batchSource+';globalThis.runtime=healthBatch;',ctx);assert.equal(JSON.stringify(ctx.runtime.clean(fixture())),JSON.stringify(m.clean(fixture())));for(const [key,pair] of Object.entries(m.labels)){assert.equal(pair.length,2);assert.ok(pair.every(x=>typeof x==='string'&&x.length));assert.notEqual(m.t(key,'en'),key);}assert.ok(!batchSource.includes('</script>'));});
test('batch preparation deduplicates exact bytes and stable manifest ignores selection order; cancellation/limits send nothing',async()=>{const p=vm.runInNewContext(photoMetadataSource+';({preparePhotoBatch})',{Uint8Array,DataView,Array,Set,Date,Number,String,Promise,Error,TextEncoder});let closed=0;const w={crypto:webcrypto,createImageBitmap:async()=>({width:2,height:2,close(){closed++;}}),document:{createElement:()=>({getContext:()=>({drawImage(){}}),toBlob:fn=>fn({size:3,arrayBuffer:async()=>Uint8Array.from([1,2,3]).buffer})})}};const file=v=>({type:'image/png',size:4,arrayBuffer:async()=>Uint8Array.from([137,80,78,v]).buffer});const a=file(1),b=file(2),one=await p.preparePhotoBatch(w,[a,b,a]),two=await p.preparePhotoBatch(w,[b,a]);assert.equal(one.images.length,2);assert.equal(one.duplicates.length,1);assert.equal(one.key,two.key);assert.ok(one.images.every(x=>x.metadata.status==='unsupported'));await assert.rejects(p.preparePhotoBatch(w,Array.from({length:9},()=>a)),/bounds/);await assert.rejects(p.preparePhotoBatch(w,[a],()=>true),/cancelled/);assert.equal(closed,5);});
test('capture corrections retain raw evidence and require explanation for date/time/zone discrepancies',()=>{const b=fixture(),c=b.sources[0].capture;c.status='available';c.exifDateTime='2026:10:03 08:15:30';c.exifOffset='+08:00';c.note='';c.userDate='2026-10-04';c.userTime='09:00';c.userTimezone='UTC-05:00';assert.ok(m.issues(m.clean(b)).includes('sourceReview'));c.note='User confirmed the device clock/offset correction; raw evidence retained';assert.deepEqual(m.issues(m.clean(b)),[]);assert.equal(m.clean(b).sources[0].capture.exifDateTime,'2026:10:03 08:15:30');assert.equal(m.clean(b).sources[0].capture.userTimezone,'UTC-05:00');});

function currentPhoto(){const b=fixture();b.sessions=b.sessions.slice(0,1);b.sources[0].kind='photo';b.sources[0].capture={...source().capture,status:'available',exifDateTime:'2026:10:01 08:15:30',exifOffset:'+08:00',note:''};const s=b.sessions[0];s.time='08:15:00';s.precision='second';s.note='';for(const o of s.observations){o.displayedDate=null;o.displayedTime=null;o.displayedTimezone=null;}return b;}
test('current-photo capture time and offset contradictions require explicit observation resolution',()=>{
 const b=currentPhoto(),s=b.sessions[0];s.time='20:00';s.precision='minute';s.timezone='UTC-05:00';assert.deepEqual(m.issues(m.clean(b)),['displayConflict']);
 for(const o of s.observations)o.resolution='User explained the scale clock mismatch and confirmed this session';assert.deepEqual(m.issues(m.clean(b)),[]);
 const c=currentPhoto();c.sources[0].capture.userDate='2026-10-01';c.sources[0].capture.userTime='20:00';c.sources[0].capture.userTimezone='UTC-05:00';c.sources[0].capture.note='User corrected the camera clock and offset';Object.assign(c.sessions[0],{time:'20:00',precision:'minute',timezone:'UTC-05:00'});assert.deepEqual(m.issues(m.clean(c)),[]);
});
test('current-photo tolerance retains minute/date precision and compares equivalent evidence-backed instants',()=>{
 const b=currentPhoto(),s=b.sessions[0];assert.deepEqual(m.issues(m.clean(b)),[]);s.time='08:20:30';assert.deepEqual(m.issues(m.clean(b)),[]);s.time='08:20:31';assert.ok(m.issues(m.clean(b)).includes('displayConflict'));
 s.time='08:10';s.precision='minute';assert.deepEqual(m.issues(m.clean(b)),[]);s.time='08:09';assert.ok(m.issues(m.clean(b)).includes('displayConflict'));
 s.time=null;s.precision='date';assert.deepEqual(m.issues(m.clean(b)),[]);
 Object.assign(s,{date:'2026-09-30',time:'19:15:30',precision:'second',timezone:'UTC-05:00'});assert.deepEqual(m.issues(m.clean(b)),[]);
});
test('historical screenshots and missing capture offsets do not acquire invented exact capture instants',()=>{
 const b=currentPhoto(),s=b.sessions[0];s.time='20:00';s.precision='minute';s.timezone='UTC-05:00';b.sources[0].kind='screenshot';assert.deepEqual(m.issues(m.clean(b)),[]);
 b.sources[0].kind='photo';b.sources[0].capture.exifOffset=null;b.sources[0].capture.note='Capture offset unavailable; device timezone not assumed';assert.deepEqual(m.issues(m.clean(b)),[]);assert.equal(m.clean(b).sources[0].capture.userTimezone,null);
});
