import {build} from 'esbuild';import {Miniflare} from 'miniflare';import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
await build({entryPoints:['tests/integration-worker.ts'],bundle:true,format:'esm',platform:'browser',external:['cloudflare:workers'],outfile:'.sites-runtime/integration-worker.mjs'});
const mf=new Miniflare({scriptPath:'.sites-runtime/integration-worker.mjs',modules:true,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'health-integration'},host:'127.0.0.1',bindings:{HEALTH_REAL_OWNER_ID:'owner-test',HEALTH_REAL_CONSENT_VERSION:'owner-photos-structured-v1'}});
try{const db=await mf.getD1Database('DB');for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort()){const sql=await readFile('drizzle/'+name,'utf8');for(const s of sql.split('--> statement-breakpoint'))await db.prepare(s.trim()).run();}
const identity=user=>({'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'});
const req=async(user,body,path='/api/health',headers={})=>{const r=await mf.dispatchFetch('http://localhost'+path,{method:body?'POST':'GET',headers:{...(user?identity(user):{}),...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
let count=0;const ok=(name,fn)=>{fn();count++;console.log('PASS',name)};
let r=await req(null);ok('unauthenticated API rejected',()=>assert.equal(r.status,401));
r=await req('alice',{action:'seed',synthetic:true});ok('synthetic seed persists 18 records',()=>assert.equal(r.data.records.length,18));
r=await req('alice',{action:'seed',synthetic:true});ok('seed deduplicates',()=>assert.equal(r.data.records.length,18));
r=await req('bob');ok('cross-user reads isolated',()=>assert.equal(r.data.records.length,0));
r=await req('alice',{action:'draft',namespace:'real',synthetic:true,record:{kind:'body'}});ok('real namespace blocked',()=>assert.equal(r.status,403));
const body={action:'draft',namespace:'demo',synthetic:true,requestKey:'same-key',record:{kind:'body',date:'2026-10-01',timezone:'Asia/Taipei',unit:'kg',weight:77.7,bodyfat:20,notes:'SYNTHETIC TEST'}};
const concurrent=await Promise.all([req('alice',body),req('alice',body)]);ok('parallel retry returns same draft',()=>{assert.equal(concurrent[0].status,200);assert.equal(concurrent[1].status,200);assert.equal(concurrent[0].data.draft.id,concurrent[1].data.draft.id);});const id=concurrent[0].data.draft.id;
r=await req('bob',{action:'confirm',draftId:id,confirmed:true});ok('cross-user confirmation rejected',()=>assert.equal(r.status,404));
r=await req('alice',{action:'confirm',draftId:id,confirmed:false});ok('confirmation required',()=>assert.equal(r.status,400));
r=await req('alice',{action:'confirm',draftId:id,confirmed:true});ok('explicit confirmation creates record',()=>assert.equal(r.data.record.weight,77.7));const saved=r.data.record.id;
r=await req('alice',{action:'confirm',draftId:id,confirmed:true});ok('confirm retry deduplicates',()=>{assert.equal(r.data.record.id,saved);assert.equal(r.data.deduplicated,true);});
r=await req('alice',{...body,requestKey:'incomplete',record:{kind:'body',weight:70}});const incomplete=r.data.draft.id;r=await req('alice',{action:'confirm',draftId:incomplete,confirmed:true});ok('missing date/unit cannot save',()=>assert.equal(r.status,422));
r=await req('alice',{...body,requestKey:'corrected',replacesDraftId:incomplete});ok('corrected draft created',()=>assert.equal(r.status,200));r=await req('alice',{action:'confirm',draftId:incomplete,confirmed:true});ok('superseded draft cannot confirm',()=>assert.equal(r.status,409));
r=await req('alice',body,'/api/health',{origin:'https://evil.example'});ok('cross-origin mutation rejected',()=>assert.equal(r.status,403));
r=await req(null,{jsonrpc:'2.0',id:1,method:'tools/list'},'/mcp');ok('MCP discovery exposes compatible legacy and batch tools',()=>assert.equal(r.data.result.tools.length,11));
r=await req(null,{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'list_health_records'}},'/mcp');ok('MCP data requires identity',()=>assert.equal(r.status,401));
r=await req('alice',{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'list_health_records'}},'/mcp');ok('MCP and web share database',()=>assert.equal(r.data.result.structuredContent.records.length,19));
r=await req(null,{jsonrpc:'2.0',id:1,method:'resources/read',params:{uri:'ui://health/records-v4.html'}},'/mcp');ok('MCP embedded resource declared',()=>{assert.equal(r.data.result.contents[0].mimeType,'text/html;profile=mcp-app');assert.match(r.data.result.contents[0].text,/ui\/message/);assert.deepEqual(r.data.result.contents[0]._meta['openai/widgetCSP'].redirect_domains,[]);assert.match(r.data.result.contents[0].text,/const siteUrl="";/);});
const actual={action:'capture',namespace:'real',userProvided:true,requestKey:'image-synthetic-fixture-0',record:{kind:'body',date:'2026-10-01',timezone:'UTC+08:00',unit:'kg',weight:72.4,bodyfat:21.6,notes:'SYNTHETIC ISOLATED FIXTURE',uncertain:[],dateEvidence:{exifDateTime:'2026:10:01 08:15:30',exifOffset:'+08:00',captureRepresentsMeasurement:true}}};
r=await req('alice',actual);ok('real capture denied for another authenticated user',()=>assert.equal(r.status,403));
r=await req('owner-test',actual);ok('owner evidence-backed capture stays draft-only',()=>{assert.equal(r.status,200);assert.equal(r.data.status,'pending');assert.equal(r.data.draft.weight,72.4);});const realDraftId=r.data.draft.id;r=await req('owner-test',{action:'confirm',draftId:realDraftId,confirmed:true});const realId=r.data.record.id;
r=await req('owner-test',actual);ok('same image entry retry returns same saved ID',()=>{assert.equal(r.data.draft.id,realDraftId);assert.equal(r.data.status,'pending');});
r=await req('owner-test',{...actual,requestKey:'different-observation-0'});ok('independent identical observation draft not collapsed',()=>assert.notEqual(r.data.draft.id,realDraftId));r=await req('owner-test',{action:'confirm',draftId:r.data.draft.id,confirmed:true});
r=await req('owner-test',{...actual,requestKey:'missing-date',record:{...actual.record,date:null,dateEvidence:{}}});ok('missing date and timezone held pending',()=>{assert.equal(r.data.status,'pending');assert.ok(r.data.issues.length);});
r=await req('owner-test',{...actual,requestKey:'conflict',record:{...actual.record,dateEvidence:{...actual.record.dateEvidence,displayedDate:'2026-09-30'}}});ok('conflicting photo and screen date held pending',()=>assert.equal(r.data.status,'pending'));
r=await req('owner-test',{...actual,requestKey:'uncertain',record:{...actual.record,uncertain:['weight']}});ok('uncertain number held pending',()=>assert.equal(r.data.status,'pending'));
r=await req('owner-test',{...actual,requestKey:'missing-unit',record:{...actual.record,unit:null}});ok('missing unit held pending',()=>assert.equal(r.data.status,'pending'));
r=await req('owner-test',null,'/api/health?namespace=demo');ok('real and synthetic namespaces isolated',()=>assert.equal(r.data.records.length,0));
r=await req('alice',{action:'delete',recordId:realId,requestKey:'not-owner'});ok('cross-owner delete denied',()=>assert.equal(r.status,404));
r=await req('owner-test',{action:'delete',recordId:realId,requestKey:'delete-first'});ok('soft delete records timestamp',()=>assert.ok(r.data.record.deleted_at));
r=await req('owner-test',null,'/api/health?namespace=real');ok('deleted excluded from chart data',()=>assert.equal(r.data.records.some(x=>x.id===realId),false));
r=await req('owner-test',null,'/api/health?namespace=real&trash=1');ok('trash contains deleted row',()=>assert.equal(r.data.records[0].id,realId));
r=await req('owner-test',actual);ok('re-upload does not resurrect deleted entry',()=>{assert.equal(r.data.status,'pending');assert.equal(r.data.draft.id,realDraftId);});
r=await req('owner-test',{action:'restore',recordId:realId,requestKey:'restore-first'});ok('explicit restore retains same ID',()=>{assert.equal(r.data.record.id,realId);assert.equal(r.data.record.deleted_at,null);});
r=await req('owner-test',{action:'delete',recordId:realId,requestKey:'delete-first'});ok('old delete retry cannot undo restore',()=>assert.equal(r.data.record.deleted_at,null));
r=await req('owner-test',{action:'restore',recordId:realId,requestKey:'delete-first'});ok('conflicting audit key rejected',()=>assert.equal(r.status,409));
r=await req('owner-test',null,'/api/health?export=1');ok('export owner-only structured data includes pending drafts',()=>{assert.equal(r.data.records.length,2);assert.ok(r.data.drafts.length>=4);assert.ok(!JSON.stringify(r.data).includes('alice'));});
r=await req(null,null,'/api/health?export=1');ok('unauthenticated export rejected',()=>assert.equal(r.status,401));
console.log('Integration checks passed:',count);
}finally{await mf.dispose();}
