import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {photoMetadataSource} from '../.sites-runtime/photo-metadata.mjs';
import {dateIssues,emptyEvidence} from '../.sites-runtime/date-evidence.mjs';
const {extractPhotoDate,preparePrivatePhoto}=vm.runInNewContext(photoMetadataSource+';({extractPhotoDate,preparePrivatePhoto})',{Uint8Array,DataView,Array,Set,Date,Number,String,Promise,Error});
function jpeg({little=true,date='2026:10:01 08:15:30',offset='+08:00',gps=true}={}){const t=new Uint8Array(140),d=new DataView(t.buffer);t[0]=little?73:77;t[1]=t[0];const s16=(at,v)=>d.setUint16(at,v,little),s32=(at,v)=>d.setUint32(at,v,little);s16(2,42);s32(4,8);s16(8,gps?2:1);s16(10,0x8769);s16(12,4);s32(14,1);s32(18,40);if(gps){s16(22,0x8825);s16(24,4);s32(26,1);s32(30,500000);}s16(40,offset===null?1:2);s16(42,0x9003);s16(44,2);s32(46,20);s32(50,80);t.set(new TextEncoder().encode(date+'\0'),80);if(offset!==null){s16(54,0x9011);s16(56,2);s32(58,7);s32(62,100);t.set(new TextEncoder().encode(offset+'\0'),100);}t.set(new TextEncoder().encode('GPS_PRIVATE_SENTINEL'),110);const length=t.length+8;return Uint8Array.from([255,216,255,225,length>>8,length&255,69,120,105,102,0,0,...t,255,218]);}
const parse=b=>extractPhotoDate(b.slice().buffer,'image/jpeg');
test('JPEG date whitelist reads little and big endian without GPS output',()=>{for(const little of [true,false]){const r=parse(jpeg({little}));assert.equal(r.status,'available');assert.equal(r.exifDateTime,'2026:10:01 08:15:30');assert.equal(r.exifOffset,'+08:00');assert.ok(!JSON.stringify(r).includes('GPS'));}});
test('missing timezone stays missing and invalid dates are rejected',()=>{assert.equal(parse(jpeg({offset:null})).exifOffset,null);for(const date of ['2026:02:30 08:00:00','2026:10:01 24:00:00'])assert.equal(parse(jpeg({date})).status,'invalid');assert.equal(parse(jpeg({offset:'+15:00'})).status,'invalid');});
test('corrupt, out of bounds and oversized EXIF are bounded',()=>{const b=jpeg();assert.equal(parse(b.subarray(0,30)).status,'invalid');const bad=jpeg();bad[16]=255;bad[17]=255;bad[18]=255;bad[19]=255;assert.equal(parse(bad).status,'invalid');assert.equal(extractPhotoDate(new ArrayBuffer(10*1024*1024+1),'image/jpeg').status,'oversized');});
test('unsupported HEIC and no EXIF cannot fabricate capture dates',()=>{assert.equal(extractPhotoDate(jpeg().buffer,'image/heic').status,'unsupported');assert.equal(parse(Uint8Array.from([255,216,255,218])).status,'missing');});
test('multiple conflicting EXIF segments remain a conflict',()=>{const a=jpeg(),b=jpeg({date:'2026:10:02 08:15:30'});const joined=Uint8Array.from([...a.subarray(0,a.length-2),...b.subarray(2)]);assert.equal(parse(joined).status,'conflict');});
const rec=(e={})=>({date:'2026-10-01',timezone:'UTC+08:00',dateEvidence:{...emptyEvidence(),exifDateTime:'2026:10:01 08:15:30',exifOffset:'+08:00',captureRepresentsMeasurement:true,...e}});
test('date evidence requires trustworthy timezone and current measurement context',()=>{assert.deepEqual(dateIssues(rec()),[]);assert.ok(dateIssues(rec({exifOffset:null})).length);assert.ok(dateIssues(rec({captureRepresentsMeasurement:false})).length);assert.ok(dateIssues(rec({displayedDate:'2026-09-30'})).length);});
test('invalid user date never falls back, explicit valid user correction resolves conflict',()=>{assert.ok(dateIssues(rec({userDate:'2026-09-31'})).length);assert.deepEqual(dateIssues(rec({displayedDate:'2026-09-30',userDate:'2026-10-01',userTimezone:'UTC+08:00'})),[]);});
test('EXIF timezone offset checked at capture instant including DST boundary',()=>{const r={date:'2026-03-08',timezone:'America/New_York',dateEvidence:{...emptyEvidence(),exifDateTime:'2026:03:08 01:30:00',exifOffset:'-05:00',captureRepresentsMeasurement:true}};assert.deepEqual(dateIssues(r),[]);assert.ok(dateIssues({...r,dateEvidence:{...r.dateEvidence,exifOffset:'-04:00'}}).length);});
test('real upload re-encodes pixels and sends neither original metadata nor GPS bytes',async()=>{const original=jpeg();let drew=false,closed=false;const w={createImageBitmap:async()=>({width:100,height:100,close(){closed=true;}}),document:{createElement(){return {getContext(){return {drawImage(){drew=true;}};},toBlob(fn,type){assert.equal(type,'image/png');fn({size:4,arrayBuffer:async()=>Uint8Array.from([137,80,78,71]).buffer});}};}},crypto:(await import('node:crypto')).webcrypto};const r=await preparePrivatePhoto(w,{type:'image/jpeg',size:original.length,arrayBuffer:async()=>original.buffer,lastModified:0});assert.equal(drew,true);assert.equal(closed,true);assert.deepEqual([...r.bytes],[137,80,78,71]);assert.equal(r.mimeType,'image/png');assert.equal(r.sourceHash.length,64);assert.equal(r.metadata.exifDateTime,'2026:10:01 08:15:30');});
