import {build} from 'esbuild';import {Miniflare} from 'miniflare';import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const mf=new Miniflare({script:'export default {fetch(){return new Response("test")}}',modules:true,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'health-races'},host:'127.0.0.1'});
try{
const db=await mf.getD1Database('DB');for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())for(const q of (await readFile('drizzle/'+name,'utf8')).split('--> statement-breakpoint'))await db.prepare(q.trim()).run();
let intercept=null;function wrap(inner,sql,args=[]){return {inner,bind(...next){return wrap(inner.bind(...next),sql,next)},async first(...a){const result=await inner.first(...a);if(intercept)await intercept(sql,args,result);return result},all:(...a)=>inner.all(...a),run:(...a)=>inner.run(...a)};}
globalThis.healthTestEnv={DB:{prepare:sql=>wrap(db.prepare(sql),sql),batch:statements=>db.batch(statements.map(s=>s.inner))},HEALTH_REAL_OWNER_ID:'race-owner',HEALTH_REAL_CONSENT_VERSION:'owner-photos-structured-v1'};
await build({entryPoints:['lib/store.ts'],bundle:true,format:'esm',platform:'node',outfile:'.sites-runtime/store-races.mjs',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'test-env',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env=globalThis.healthTestEnv;',loader:'js'}));}}]});
const {createDraft,confirmDraft,changeRecord,captureRecord}=await import('../.sites-runtime/store-races.mjs?'+Date.now());
const record={kind:'body',date:'2026-10-01',timezone:'Asia/Taipei',unit:'kg',weight:70,bodyfat:20,notes:'ISOLATED SYNTHETIC FIXTURE',uncertain:[],dateEvidence:{userDate:'2026-10-01',userTimezone:'Asia/Taipei'}};
const a={namespace:'real',userProvided:true,requestKey:'draft-original',record};const initial=await createDraft('race-owner',a);
let release;let reached;const waiting=new Promise(r=>reached=r),gate=new Promise(r=>release=r);intercept=async(sql,args)=>{if(sql.includes('FROM health_drafts WHERE owner_id=? AND id=?')&&args[1]===initial.draft.id){reached();await gate;}};
const stale=confirmDraft('race-owner',{draftId:initial.draft.id,confirmed:true});await waiting;intercept=null;await createDraft('race-owner',{...a,requestKey:'corrected',replacesDraftId:initial.draft.id,record:{...record,weight:71}});release();await assert.rejects(stale,{status:409});assert.equal((await db.prepare('SELECT COUNT(*) n FROM health_records').first()).n,0);console.log('PASS concurrent replacement prevents stale confirmation');
const captured=await captureRecord('race-owner',{...a,requestKey:'for-delete-race'});const saved=await confirmDraft('race-owner',{draftId:captured.draft.id,confirmed:true});const id=saved.record.id;let release1,release2,count=0,ready;const both=new Promise(r=>ready=r),gate1=new Promise(r=>release1=r),gate2=new Promise(r=>release2=r);intercept=async(sql,args,result)=>{if(sql.startsWith('SELECT record_id,action FROM health_events')&&args[1]==='same-delete'&&!result){count++;if(count===2)ready();await(count===1?gate1:gate2);}};
const d1=changeRecord('race-owner',{recordId:id,requestKey:'same-delete'},'delete'),d2=changeRecord('race-owner',{recordId:id,requestKey:'same-delete'},'delete');await both;release1();await d1;intercept=null;await changeRecord('race-owner',{recordId:id,requestKey:'interleaved-restore'},'restore');release2();await d2;assert.equal((await db.prepare('SELECT deleted_at FROM health_records WHERE id=?').bind(id).first()).deleted_at,null);assert.equal((await db.prepare("SELECT COUNT(*) n FROM health_events WHERE request_key='same-delete'").first()).n,1);console.log('PASS delayed concurrent delete retry cannot undo restore');

await build({entryPoints:['lib/batch-store.ts'],bundle:true,format:'esm',platform:'node',outfile:'.sites-runtime/batch-races.mjs',plugins:[{name:'test-env-batches',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'test-env',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env=globalThis.healthTestEnv;',loader:'js'}));}}]});
const {createBatchDraft,confirmBatchDraft,changeBatch}=await import('../.sites-runtime/batch-races.mjs?'+Date.now());const {fixture}=await import('./batch-fixtures.mjs');
const batchArgs={namespace:'real',userProvided:true,requestKey:'batch-race-original',batch:fixture()};const original=await createBatchDraft('race-owner',batchArgs);
{
 let unlock,reached;const waiting=new Promise(r=>reached=r),gate=new Promise(r=>unlock=r);intercept=async(sql,args)=>{if(sql.startsWith('SELECT * FROM health_batch_drafts WHERE owner_id=? AND id=?')&&args[1]===original.draft.id){reached();await gate;}};
 const stale=confirmBatchDraft('race-owner',{draftId:original.draft.id,expectedDigest:original.draft.digest,confirmed:true});await waiting;intercept=null;const changed=fixture();changed.sessions[0].observations[0].value=73;await createBatchDraft('race-owner',{...batchArgs,requestKey:'batch-race-corrected',replacesDraftId:original.draft.id,expectedDigest:original.draft.digest,batch:changed});unlock();await assert.rejects(stale,{status:409});assert.equal((await db.prepare('SELECT COUNT(*) n FROM health_batches').first()).n,0);console.log('PASS batch replacement blocks stale confirmation after read');
}
{
 const old=await createBatchDraft('race-owner',{...batchArgs,requestKey:'batch-competing-original'});const changes=await Promise.allSettled(['one','two'].map((suffix,i)=>{const batch=fixture();batch.sessions[0].observations[0].value=70+i;return createBatchDraft('race-owner',{...batchArgs,requestKey:'batch-competing-'+suffix,replacesDraftId:old.draft.id,expectedDigest:old.draft.digest,batch});}));assert.equal(changes.filter(r=>r.status==='fulfilled').length,1);assert.equal(changes.find(r=>r.status==='rejected').reason.status,409);console.log('PASS only one competing batch replacement can supersede reviewed version');
}
{
 const created=await createBatchDraft('race-owner',{...batchArgs,requestKey:'batch-parallel-create'});const confirmations=await Promise.all(Array.from({length:5},()=>confirmBatchDraft('race-owner',{draftId:created.draft.id,expectedDigest:created.draft.digest,confirmed:true})));assert.equal(new Set(confirmations.map(c=>c.record.id)).size,1);assert.equal((await db.prepare('SELECT COUNT(*) n FROM health_batches').first()).n,1);const id=confirmations[0].record.id;
 let release1,release2,count=0,ready;const both=new Promise(r=>ready=r),g1=new Promise(r=>release1=r),g2=new Promise(r=>release2=r);intercept=async(sql,args,result)=>{if(sql.startsWith('SELECT record_id,action FROM health_events')&&args[1]==='same-batch-delete'&&!result){count++;if(count===2)ready();await(count===1?g1:g2);}};
 const one=changeBatch('race-owner',{batchId:id,requestKey:'same-batch-delete',confirmed:true},'delete'),two=changeBatch('race-owner',{batchId:id,requestKey:'same-batch-delete',confirmed:true},'delete');await both;release1();await one;intercept=null;await changeBatch('race-owner',{batchId:id,requestKey:'batch-interleaved-restore',confirmed:true},'restore');release2();await two;assert.equal((await db.prepare('SELECT deleted_at FROM health_batches WHERE id=?').bind(id).first()).deleted_at,null);console.log('PASS parallel whole-batch confirm deduplicates and delayed delete retry cannot undo restore');
}
}finally{delete globalThis.healthTestEnv;await mf.dispose();}
