import {build} from 'esbuild';import {Miniflare} from 'miniflare';import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const mf=new Miniflare({script:'export default {fetch(){return new Response("test")}}',modules:true,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'health-races'},host:'127.0.0.1'});
try{
const db=await mf.getD1Database('DB');for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())for(const q of (await readFile('drizzle/'+name,'utf8')).split('--> statement-breakpoint'))await db.prepare(q.trim()).run();
let intercept=null;function wrap(inner,sql,args=[]){return {inner,bind(...next){return wrap(inner.bind(...next),sql,next)},async first(...a){const result=await inner.first(...a);if(intercept)await intercept(sql,args,result);return result},all:(...a)=>inner.all(...a),run:(...a)=>inner.run(...a)};}
globalThis.healthTestEnv={DB:{prepare:sql=>wrap(db.prepare(sql),sql),batch:statements=>db.batch(statements.map(s=>s.inner))},HEALTH_REAL_OWNER_ID:'race-owner',HEALTH_REAL_CONSENT_VERSION:'owner-photos-structured-v1'};
await build({entryPoints:['lib/store.ts'],bundle:true,format:'esm',platform:'node',outfile:'.sites-runtime/store-races.mjs',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'test-env',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env=globalThis.healthTestEnv;',loader:'js'}));}}]});
const {createDraft,confirmDraft,changeRecord,captureRecord}=await import('../.sites-runtime/store-races.mjs?'+Date.now());
const record={kind:'body',date:'2026-10-01',timezone:'Asia/Taipei',unit:'kg',weight:70,bodyfat:20,notes:'ISOLATED SYNTHETIC FIXTURE',uncertain:[],dateEvidence:{userDate:'2026-10-01',userTimezone:'Asia/Taipei'}};
const a={namespace:'real',userProvided:true,requestKey:'draft-original',record};const initial=await createDraft('race-owner',a);
let release;let reached;const waiting=new Promise(r=>reached=r),gate=new Promise(r=>release=r);intercept=async(sql,args)=>{if(sql.includes('FROM health_drafts WHERE owner_id=? AND id=?')&&args[1]===initial.draft.id){reached();await gate;}};
const stale=confirmDraft('race-owner',{draftId:initial.draft.id,confirmed:true});await waiting;intercept=null;await createDraft('race-owner',{...a,requestKey:'corrected',replacesDraftId:initial.draft.id,record:{...record,weight:71}});release();await assert.rejects(stale,{status:409});assert.equal((await db.prepare('SELECT COUNT(*) n FROM health_records').first()).n,0);console.log('PASS concurrent replacement prevents stale confirmation');
const saved=await captureRecord('race-owner',{...a,requestKey:'for-delete-race'});const id=saved.record.id;let release1,release2,count=0,ready;const both=new Promise(r=>ready=r),gate1=new Promise(r=>release1=r),gate2=new Promise(r=>release2=r);intercept=async(sql,args,result)=>{if(sql.startsWith('SELECT record_id,action FROM health_events')&&args[1]==='same-delete'&&!result){count++;if(count===2)ready();await(count===1?gate1:gate2);}};
const d1=changeRecord('race-owner',{recordId:id,requestKey:'same-delete'},'delete'),d2=changeRecord('race-owner',{recordId:id,requestKey:'same-delete'},'delete');await both;release1();await d1;intercept=null;await changeRecord('race-owner',{recordId:id,requestKey:'interleaved-restore'},'restore');release2();await d2;assert.equal((await db.prepare('SELECT deleted_at FROM health_records WHERE id=?').bind(id).first()).deleted_at,null);assert.equal((await db.prepare("SELECT COUNT(*) n FROM health_events WHERE request_key='same-delete'").first()).n,1);console.log('PASS delayed concurrent delete retry cannot undo restore');
}finally{delete globalThis.healthTestEnv;await mf.dispose();}
