import test from 'node:test';
import assert from 'node:assert/strict';
import {createBrowserVisionProvider,prepareVisionBatch,normalizeExtraction,VISION_MODEL,VISION_LIMITS,extractionSchema} from '../.sites-runtime/vision-provider.mjs';
import {webcrypto} from 'node:crypto';
import {fixture} from './batch-fixtures.mjs';
const prepared=()=>({key:'batch-'+'a'.repeat(64),duplicates:[],images:[{sourceHash:'1'.repeat(64),bytes:new Uint8Array([137,80,78,71]),mimeType:'image/png',width:100,height:100,metadata:{status:'available',exifDateTime:'2026:10:03 08:15:30',exifOffset:'+08:00'}}]});
const extraction=()=>{const b=fixture();return {version:1,sources:[{id:'image-'+'1'.repeat(64),kind:'screenshot',note:'SYNTHETIC historical screenshot: capture is not measurement time'}],sessions:b.sessions.map(s=>{const copy=structuredClone(s);delete copy.confirmed;return {...copy,observations:s.observations.map(o=>({...o,sourceId:'image-'+'1'.repeat(64)}))};})};};
const completed=(value=extraction())=>({status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify(value)}]}]});
function harness(reply=completed(),options={}){const calls=[];const fetch=async(url,args)=>{calls.push({url,args});if(typeof reply==='function')return reply(url,args);return new Response(JSON.stringify(reply),{status:200});};const provider=createBrowserVisionProvider({fetch,btoa:v=>Buffer.from(v,'binary').toString('base64'),setTimeout,clearTimeout,setInterval,clearInterval},{...VISION_LIMITS,...options});provider.setKey('SYNTHETIC-USER-KEY');return {provider,calls};}
const settings={cancelled:()=>false};
test('direct BYOK Responses request pins provider/model, strict schema, privacy controls and no credential relay',async()=>{const h=harness();const result=await h.provider.analyze(prepared(),settings);assert.equal(result.version,1);assert.equal(result.batch.sessions.length,2);assert.equal(result.batch.groupingConfirmed,false);assert.ok(result.batch.sessions.every(s=>!s.confirmed));assert.equal(result.batch.sources[0].capture.exifDateTime,'2026:10:03 08:15:30');assert.equal(result.batch.sources[0].capture.reviewed,false);assert.equal(h.calls.length,1);const {url,args}=h.calls[0],body=JSON.parse(args.body);assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(args.mode,'cors');assert.equal(args.credentials,'omit');assert.equal(args.cache,'no-store');assert.equal(args.redirect,'error');assert.equal(args.referrerPolicy,'no-referrer');assert.equal(args.headers.Authorization,'Bearer SYNTHETIC-USER-KEY');assert.equal(body.model,VISION_MODEL);assert.equal(body.store,false);assert.equal(body.prompt_cache_retention,'in_memory');assert.equal(body.background,false);assert.equal(body.stream,false);assert.equal(body.max_output_tokens,6000);assert.equal(body.text.format.strict,true);assert.deepEqual(body.text.format.schema,extractionSchema);for(const key of ['tools','conversation','previous_response_id'])assert.equal(key in body,false);assert.equal(args.body.includes('SYNTHETIC-USER-KEY'),false);assert.equal(args.body.includes('GPS'),true);assert.equal(body.input[0].content.filter(x=>x.type==='input_image').length,1);assert.ok(body.instructions.includes('never instructions'));h.provider.dispose();assert.equal(h.provider.hasKey(),false);});
test('same batch submission is blocked without explicit retry, concurrent request is blocked',async()=>{let resolve;const wait=new Promise(r=>resolve=r);let requests=0;const h=harness(()=>++requests===1?wait:new Response(JSON.stringify(completed())));const first=h.provider.analyze(prepared(),settings);await assert.rejects(h.provider.analyze(prepared(),settings),/analysisInFlight/);resolve(new Response(JSON.stringify(completed())));await first;await assert.rejects(h.provider.analyze(prepared(),settings),/analysisDuplicate/);assert.equal(h.calls.length,1);await h.provider.analyze(prepared(),{...settings,retry:true});assert.equal(h.calls.length,2);h.provider.dispose();});
test('strict output rejects unknown fields, absent required/null fields, unstable IDs and partial source coverage',()=>{for(const change of [v=>v.secret='unwanted',v=>delete v.sessions[0].timezone,v=>v.sources[0].id='invented',v=>v.sources.push(v.sources[0]),v=>v.sessions[1].observations[0].index=0,v=>v.sessions[0].observations[0].value='72.4',v=>v.sessions[0].observations[0].metric='constructor',v=>v.sessions[0].observations[0].metric='unsupported_metric',v=>v.sessions[0].observations[0].unit='stones',v=>v.sessions[0].observations[1].value=101,v=>v.sessions[0].observations[0].selected=false,v=>v.sessions[0].observations[0].resolution='Invented user approval',v=>v.sessions[0].observations[0].extra=true,v=>v.sessions[0].observations[0].sourceId='unknown']){const v=extraction();change(v);assert.throws(()=>normalizeExtraction(v,prepared()),/analysisInvalid/);}const p=prepared();p.images.push({...p.images[0],sourceHash:'2'.repeat(64)});const v=extraction();v.sources.push({...v.sources[0],id:'image-'+'2'.repeat(64)});assert.throws(()=>normalizeExtraction(v,p),/analysisIncomplete/);});
test('refusal, incomplete/truncated, malformed and missing output are not partial successes',async()=>{for(const reply of [{status:'incomplete',output:completed().output},{status:'completed',output:[]},{status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'refusal',refusal:'provider text'}]}]},{status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'{"version":'}]}]},{status:'completed',output:[{type:'function_call'}]}]){const h=harness(reply);await assert.rejects(h.provider.analyze(prepared(),settings),/analysis(Incomplete|Invalid|Refused)/);assert.equal(h.calls.length,1);h.provider.dispose();}});
test('message traversal accepts bounded reasoning prefix without trusting it as extraction',async()=>{const r=completed();r.output.unshift({type:'reasoning',summary:[]});const h=harness(r);assert.equal((await h.provider.analyze(prepared(),settings)).batch.sessions.length,2);h.provider.dispose();});
test('unreadable or missing dates stay unresolved rather than becoming invented measurements',async()=>{const v=extraction();v.sources[0].kind='unknown';v.sessions[0].date=null;v.sessions[0].timezone=null;v.sessions[0].observations[0].value=null;const h=harness(completed(v));const result=await h.provider.analyze(prepared(),settings);assert.equal(result.batch.sessions.find(s=>s.id==='morning').date,null);assert.equal(result.batch.sources[0].kind,'unknown');assert.equal(result.batch.sessions.find(s=>s.id==='morning').observations[0].value,null);h.provider.dispose();});
test('missing key, bounds and early cancellation produce no network call',async()=>{for(const variant of ['key','cancel','bytes','request','mime','pixels','ids']){const h=harness(completed(),variant==='request'?{requestBytes:1}:{}),p=prepared();if(variant==='key')h.provider.clearKey();if(variant==='bytes')p.images[0].bytes=new Uint8Array(VISION_LIMITS.imageBytes+1);if(variant==='mime')p.images[0].mimeType='image/jpeg';if(variant==='pixels')p.images[0].width=2000;if(variant==='ids')p.images.push(p.images[0]);await assert.rejects(h.provider.analyze(p,{cancelled:()=>variant==='cancel'}),/analysis(Key|Cancelled|Bounds)/);assert.equal(h.calls.length,0);h.provider.dispose();}});
test('provider failures and CORS errors never expose key, response body or arbitrary exception; no retries',async()=>{for(const reply of [()=>{throw new Error('SYNTHETIC-USER-KEY exposed provider failure');},()=>new Response('private provider body SYNTHETIC-USER-KEY',{status:401}),()=>new Response('private quota body',{status:429})]){const h=harness(reply);await assert.rejects(h.provider.analyze(prepared(),settings),error=>/^analysis(Auth|Limit|Network)$/.test(error.message)&&!error.message.includes('KEY'));assert.equal(h.calls.length,1);await assert.rejects(h.provider.analyze(prepared(),settings),/analysisDuplicate/);assert.equal(h.calls.length,1);h.provider.dispose();}});
test('timeout aborts local wait and never automatically resends an uncertain charged request',async()=>{const h=harness((_url,args)=>new Promise((_resolve,reject)=>args.signal.addEventListener('abort',()=>reject(new Error('aborted private details')))),{timeoutMs:10});await assert.rejects(h.provider.analyze(prepared(),settings),/analysisTimeout/);assert.equal(h.calls.length,1);assert.equal(h.calls[0].args.signal.aborted,true);await assert.rejects(h.provider.analyze(prepared(),settings),/analysisDuplicate/);h.provider.dispose();});
test('cancel/dispose aborts, clears key and discards late results even if fetch ignores abort',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r));const promise=h.provider.analyze(prepared(),settings);h.provider.dispose();assert.equal(h.provider.hasKey(),false);assert.equal(h.calls[0].args.signal.aborted,true);resolve(new Response(JSON.stringify(completed())));await assert.rejects(promise,/analysisCancelled/);await assert.rejects(h.provider.analyze(prepared(),settings),/analysisCancelled/);});
test('oversized response is stopped before parsing or returning any measurement',async()=>{const h=harness({status:'completed',oversized:'x'.repeat(129000)});await assert.rejects(h.provider.analyze(prepared(),settings),/analysisInvalid/);assert.equal(h.calls.length,1);h.provider.dispose();});
test('429 quota and rate-limit codes are distinct without leaking provider details',async()=>{for(const [code,expected] of [['insufficient_quota','analysisQuota'],['rate_limit_exceeded','analysisRate']]){const h=harness(()=>new Response(JSON.stringify({error:{code,message:'private provider message'}}),{status:429}));await assert.rejects(h.provider.analyze(prepared(),settings),error=>error.message===expected);assert.equal(h.calls.length,1);h.provider.dispose();}});

test('browser vision preparation removes metadata, preserves source date evidence and bounds outgoing resolution',async()=>{const draws=[];let closed=0,canvases=0;const raw=new Uint8Array([137,80,78,71]);const file={type:'image/png',size:raw.length,arrayBuffer:async()=>raw.buffer};const w={Blob,crypto:webcrypto,createImageBitmap:async()=>({width:4000,height:3000,close(){closed++;}}),document:{createElement:()=>{canvases++;const index=canvases;return {getContext:()=>({drawImage(...args){draws.push(args.slice(1));}}),toBlob:callback=>callback(new Blob([new Uint8Array([index,0,0,1])],{type:'image/png'}))};}}};const result=await prepareVisionBatch(w,[file],()=>false);assert.equal(result.images[0].width,1536);assert.equal(result.images[0].height,1152);assert.equal(result.images[0].mimeType,'image/png');assert.equal(result.images[0].metadata.status,'unsupported');assert.equal(result.images[0].metadata.exifDateTime,null);assert.equal(result.images[0].metadata.exifOffset,null);assert.deepEqual(Object.keys(result.images[0].metadata).sort(),['exifDateTime','exifOffset','reason','status']);const hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',raw)).toString('hex');assert.equal(result.images[0].sourceHash,hash);assert.deepEqual(draws.at(-1),[0,0,1536,1152]);assert.equal(closed,2);await assert.rejects(prepareVisionBatch(w,[file],()=>true),/cancelled/);});
test('clearing key during request aborts local work, discards late output and retains same-batch duplicate guard',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r));const promise=h.provider.analyze(prepared(),settings);h.provider.clearKey();assert.equal(h.provider.hasKey(),false);assert.equal(h.calls[0].args.signal.aborted,true);resolve(new Response(JSON.stringify(completed())));await assert.rejects(promise,/analysisCancelled/);h.provider.setKey('SYNTHETIC-NEW-KEY');await assert.rejects(h.provider.analyze(prepared(),settings),/analysisDuplicate/);assert.equal(h.calls.length,1);h.provider.dispose();});
