import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import {i18n} from '../.sites-runtime/i18n.mjs';import {bridgeSource} from '../.sites-runtime/widget-bridge.mjs';
const factory=vm.runInNewContext(bridgeSource+';createHealthBridge',{Map,Promise,Error,Uint8Array,String,Object});
function harness(caps,settings={}){const calls=[];let listener;const parent={postMessage(message,origin){calls.push({message,origin});if(message.id===undefined)return;queueMicrotask(()=>{let result=message.method==='ui/initialize'?{hostCapabilities:caps,protocolVersion:'2026-01-26'}:settings.results?.[message.method]||{};listener?.({source:settings.spoof?{}:parent,origin:'https://chatgpt.com',data:{jsonrpc:'2.0',id:message.id,result}});});}};const w={parent,setTimeout,clearTimeout,crypto:webcrypto,btoa:s=>Buffer.from(s,'binary').toString('base64'),addEventListener:(name,fn)=>listener=fn,removeEventListener:()=>listener=null};if(settings.real){w.createImageBitmap=async()=>({width:2,height:2,close(){}});w.document={createElement:()=>({getContext:()=>({drawImage(){}}),toBlob:fn=>fn({size:3,arrayBuffer:async()=>Uint8Array.from([1,2,3]).buffer})})};}let reads=0;const file={type:'image/png',size:4,arrayBuffer:async()=>{reads++;return Uint8Array.from([137,80,78,71]).buffer;}};const bridge=factory(w,{timeoutMs:70,...(settings.locale?{translate:text=>i18n.message(text,settings.locale),locale:()=>settings.locale}:{})});return {bridge,calls,file,reads:()=>reads};}
test('direct image message contains actual bytes, default read-only',async()=>{const h=harness({message:{text:{},image:{}}});try{const result=await h.bridge.sendImage(h.file);assert.equal(result.route,'message');const call=h.calls.find(x=>x.message.method==='ui/message');assert.equal(call.message.params.role,'user');assert.equal(call.message.params.content[1].type,'image');assert.equal(call.message.params.content[1].mimeType,'image/png');assert.equal(call.message.params.content[1].data,'iVBORw==');assert.match(call.message.params.content[0].text,/不得建立草稿/);assert.equal(call.origin,'https://chatgpt.com');assert.ok(h.calls.some(x=>x.message.method==='ui/notifications/initialized'));}finally{h.bridge.dispose();}});
test('draft permission only included after explicit opt-in',async()=>{const h=harness({message:{text:{},image:{}}});try{await h.bridge.sendImage(h.file,true);const c=h.calls.find(x=>x.message.method==='ui/message').message.params.content;assert.match(c[0].text,/我在介面另外勾選了/);assert.match(c[0].text,/不得呼叫 confirm_health_draft/);}finally{h.bridge.dispose();}});
test('image context route waits for context acknowledgment',async()=>{const h=harness({message:{text:{}},updateModelContext:{image:{}}});try{assert.equal((await h.bridge.sendImage(h.file)).route,'context');const methods=h.calls.map(x=>x.message.method);assert.ok(methods.indexOf('ui/update-model-context')<methods.indexOf('ui/message'));const ctx=h.calls.find(x=>x.message.method==='ui/update-model-context');assert.equal(ctx.message.params.content[0].data,'iVBORw==');}finally{h.bridge.dispose();}});
test('text-only host sends neither image nor analysis text',async()=>{const h=harness({message:{text:{}}});try{await assert.rejects(h.bridge.sendImage(h.file),/未宣告支援/);assert.equal(h.reads(),0);assert.equal(h.calls.some(x=>x.message.method==='ui/message'),false);}finally{h.bridge.dispose();}});
test('host message rejection is not reported as accepted',async()=>{const h=harness({message:{text:{},image:{}}},{results:{'ui/message':{isError:true}}});try{await assert.rejects(h.bridge.sendImage(h.file),/未接受/);}finally{h.bridge.dispose();}});
test('rejected image context never sends a text request',async()=>{const h=harness({message:{text:{}},updateModelContext:{image:{}}},{results:{'ui/update-model-context':{isError:true}}});try{await assert.rejects(h.bridge.sendImage(h.file),/未接受圖片/);assert.equal(h.calls.some(x=>x.message.method==='ui/message'),false);}finally{h.bridge.dispose();}});
test('only the iframe parent can complete handshake',async()=>{const h=harness({message:{text:{},image:{}}},{spoof:true});try{await assert.rejects(h.bridge.sendImage(h.file),/逾時/);assert.equal(h.reads(),0);}finally{h.bridge.dispose();}});
test('MIME and size checked before bytes leave browser',async()=>{const h=harness({message:{text:{},image:{}}});try{await assert.rejects(h.bridge.sendImage({...h.file,type:'text/plain'}),/PNG/);await assert.rejects(h.bridge.sendImage({...h.file,size:11*1024*1024}),/10 MB/);assert.equal(h.reads(),0);}finally{await h.bridge.ready;h.bridge.dispose();}});

test('real image bridge sends sanitized pixels, actual metadata status, and stable source key',async()=>{const h=harness({message:{text:{},image:{}}},{real:true});try{await h.bridge.sendImage(h.file,false,{real:true});await h.bridge.sendImage(h.file,false,{real:true});const messages=h.calls.filter(x=>x.message.method==='ui/message').map(x=>x.message.params.content);assert.equal(messages[0][1].data,'AQID');assert.equal(messages[0][1].mimeType,'image/png');assert.match(messages[0][0].text,/"status":"unsupported"/);assert.match(messages[0][0].text,/capture_health_record/);assert.equal(messages[0][0].text.match(/image-[a-f0-9]{64}/)[0],messages[1][0].text.match(/image-[a-f0-9]{64}/)[0]);assert.match(messages[0][0].text,/不得把檔案修改時間/);}finally{h.bridge.dispose();}});
test('real image read-only mode never authorizes writes',async()=>{const h=harness({message:{text:{},image:{}}},{real:true});try{await h.bridge.sendImage(h.file,false,{real:true,readOnly:true});const text=h.calls.find(x=>x.message.method==='ui/message').message.params.content[0].text;assert.match(text,/禁止任何寫入工具/);assert.doesNotMatch(text,/呼叫 capture_health_record/);}finally{h.bridge.dispose();}});
test('English synthetic/read-only prompts retain consent boundaries and stable tool identifiers',async()=>{
  const h=harness({message:{text:{},image:{}}},{locale:'en'});
  try{await h.bridge.sendImage(h.file,false);const text=h.calls.find(x=>x.message.method==='ui/message').message.params.content[0].text;assert.match(text,/Do not create drafts, save records or call any write tool/);assert.match(text,/Do not guess/);assert.match(text,/Respond in the current interface language: en/);assert.doesNotMatch(text,/請只根據/);}finally{h.bridge.dispose();}
});
test('English real-image prompt keeps source/date rules and read-only setting without mutation',async()=>{
  const h=harness({message:{text:{},image:{}}},{locale:'en',real:true});
  try{await h.bridge.sendImage(h.file,false,{real:true,readOnly:true});const text=h.calls.find(x=>x.message.method==='ui/message').message.params.content[0].text;assert.match(text,/No write tools are allowed/);assert.match(text,/Never use file modification time, upload time, today or server time/);assert.match(text,/dateEvidence.metadataStatus/);assert.match(text,/image-[a-f0-9]{64}/);assert.doesNotMatch(text,/call capture_health_record/);}finally{h.bridge.dispose();}
});
const preparedBatch=()=>({key:'batch-'+'a'.repeat(64),images:[{sourceHash:'1'.repeat(64),bytes:Uint8Array.from([1,2]),metadata:{status:'missing',exifDateTime:null,exifOffset:null}},{sourceHash:'2'.repeat(64),bytes:Uint8Array.from([3,4]),metadata:{status:'available',exifDateTime:'2026:10:02 09:00:00',exifOffset:'+08:00'}}]});
test('whole batch message includes all sanitized images, one-to-many evidence and draft-only permission',async()=>{const h=harness({message:{text:{},image:{}}},{locale:'en'});try{const sent=await h.bridge.sendBatch(preparedBatch(),{allowDraft:true,namespace:'demo'});assert.equal(sent.count,2);const c=h.calls.find(x=>x.message.method==='ui/message').message.params.content;assert.equal(c.length,3);assert.equal(c[1].data,'AQI=');assert.equal(c[2].data,'AwQ=');assert.match(c[0].text,/one screenshot can contain multiple dated observations/);assert.match(c[0].text,/create_health_batch_draft/);assert.match(c[0].text,/NEVER call any confirmation/);assert.match(c[0].text,/"reviewed":false/);assert.doesNotMatch(c[0].text,/GPS|file_name|download_url/);}finally{h.bridge.dispose();}});
test('whole batch context route sends all images once; failure never falls through to text-only',async()=>{const h=harness({message:{text:{}},updateModelContext:{image:{}}},{results:{'ui/update-model-context':{isError:true}}});try{await assert.rejects(h.bridge.sendBatch(preparedBatch()),/partial/);assert.equal(h.calls.find(x=>x.message.method==='ui/update-model-context').message.params.content.length,2);assert.ok(!h.calls.some(x=>x.message.method==='ui/message'));}finally{h.bridge.dispose();}});
test('batch unknown host, duplicate source IDs and oversized batches fail closed',async()=>{const h=harness({message:{text:{}}});try{await assert.rejects(h.bridge.sendBatch(preparedBatch()),/transportMissing/);assert.ok(!h.calls.some(x=>x.message.method==='ui/message'));}finally{h.bridge.dispose();}const ready=harness({message:{text:{},image:{}}});try{const p=preparedBatch();p.images.push(p.images[0]);await assert.rejects(ready.bridge.sendBatch(p),/bounds/);assert.ok(!ready.calls.some(x=>x.message.method==='ui/message'));}finally{ready.bridge.dispose();}});
test('cancel before host readiness prevents any batch images/text; after context acceptance is uncertain',async()=>{const h=harness({message:{text:{},image:{}}});try{await assert.rejects(h.bridge.sendBatch(preparedBatch(),{cancelled:()=>true}),/cancelled/);assert.ok(!h.calls.some(x=>x.message.method==='ui/message'));}finally{h.bridge.dispose();}const ctx=harness({message:{text:{}},updateModelContext:{image:{}}});let checks=0;try{await assert.rejects(ctx.bridge.sendBatch(preparedBatch(),{cancelled:()=>++checks>2}),/partial/);assert.ok(ctx.calls.some(x=>x.message.method==='ui/update-model-context'));assert.ok(!ctx.calls.some(x=>x.message.method==='ui/message'));}finally{ctx.bridge.dispose();}});
