import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import {bridgeSource} from '../.sites-runtime/widget-bridge.mjs';
const factory=vm.runInNewContext(bridgeSource+';createHealthBridge',{Map,Promise,Error,Uint8Array,String,Object});
function harness(caps,settings={}){const calls=[];let listener;const parent={postMessage(message,origin){calls.push({message,origin});if(message.id===undefined)return;queueMicrotask(()=>{let result=message.method==='ui/initialize'?{hostCapabilities:caps,protocolVersion:'2026-01-26'}:settings.results?.[message.method]||{};listener?.({source:settings.spoof?{}:parent,origin:'https://chatgpt.com',data:{jsonrpc:'2.0',id:message.id,result}});});}};const w={parent,setTimeout,clearTimeout,crypto:webcrypto,btoa:s=>Buffer.from(s,'binary').toString('base64'),addEventListener:(name,fn)=>listener=fn,removeEventListener:()=>listener=null};if(settings.real){w.createImageBitmap=async()=>({width:2,height:2,close(){}});w.document={createElement:()=>({getContext:()=>({drawImage(){}}),toBlob:fn=>fn({size:3,arrayBuffer:async()=>Uint8Array.from([1,2,3]).buffer})})};}let reads=0;const file={type:'image/png',size:4,arrayBuffer:async()=>{reads++;return Uint8Array.from([137,80,78,71]).buffer;}};const bridge=factory(w,{timeoutMs:70});return {bridge,calls,file,reads:()=>reads};}
test('direct image message contains actual bytes, default read-only',async()=>{const h=harness({message:{text:{},image:{}}});try{const result=await h.bridge.sendImage(h.file);assert.equal(result.route,'message');const call=h.calls.find(x=>x.message.method==='ui/message');assert.equal(call.message.params.role,'user');assert.equal(call.message.params.content[1].type,'image');assert.equal(call.message.params.content[1].mimeType,'image/png');assert.equal(call.message.params.content[1].data,'iVBORw==');assert.match(call.message.params.content[0].text,/不得建立草稿/);assert.equal(call.origin,'https://chatgpt.com');assert.ok(h.calls.some(x=>x.message.method==='ui/notifications/initialized'));}finally{h.bridge.dispose();}});
test('draft permission only included after explicit opt-in',async()=>{const h=harness({message:{text:{},image:{}}});try{await h.bridge.sendImage(h.file,true);const c=h.calls.find(x=>x.message.method==='ui/message').message.params.content;assert.match(c[0].text,/我在介面另外勾選了/);assert.match(c[0].text,/不得呼叫 confirm_health_draft/);}finally{h.bridge.dispose();}});
test('image context route waits for context acknowledgment',async()=>{const h=harness({message:{text:{}},updateModelContext:{image:{}}});try{assert.equal((await h.bridge.sendImage(h.file)).route,'context');const methods=h.calls.map(x=>x.message.method);assert.ok(methods.indexOf('ui/update-model-context')<methods.indexOf('ui/message'));const ctx=h.calls.find(x=>x.message.method==='ui/update-model-context');assert.equal(ctx.message.params.content[0].data,'iVBORw==');}finally{h.bridge.dispose();}});
test('text-only host sends neither image nor analysis text',async()=>{const h=harness({message:{text:{}}});try{await assert.rejects(h.bridge.sendImage(h.file),/未宣告支援/);assert.equal(h.reads(),0);assert.equal(h.calls.some(x=>x.message.method==='ui/message'),false);}finally{h.bridge.dispose();}});
test('host message rejection is not reported as accepted',async()=>{const h=harness({message:{text:{},image:{}}},{results:{'ui/message':{isError:true}}});try{await assert.rejects(h.bridge.sendImage(h.file),/未接受/);}finally{h.bridge.dispose();}});
test('rejected image context never sends a text request',async()=>{const h=harness({message:{text:{}},updateModelContext:{image:{}}},{results:{'ui/update-model-context':{isError:true}}});try{await assert.rejects(h.bridge.sendImage(h.file),/未接受圖片/);assert.equal(h.calls.some(x=>x.message.method==='ui/message'),false);}finally{h.bridge.dispose();}});
test('only the iframe parent can complete handshake',async()=>{const h=harness({message:{text:{},image:{}}},{spoof:true});try{await assert.rejects(h.bridge.sendImage(h.file),/逾時/);assert.equal(h.reads(),0);}finally{h.bridge.dispose();}});
test('MIME and size checked before bytes leave browser',async()=>{const h=harness({message:{text:{},image:{}}});try{await assert.rejects(h.bridge.sendImage({...h.file,type:'text/plain'}),/PNG/);await assert.rejects(h.bridge.sendImage({...h.file,size:11*1024*1024}),/10 MB/);assert.equal(h.reads(),0);}finally{await h.bridge.ready;h.bridge.dispose();}});

test('real image bridge sends sanitized pixels, actual metadata status, and stable source key',async()=>{const h=harness({message:{text:{},image:{}}},{real:true});try{await h.bridge.sendImage(h.file,false,{real:true});await h.bridge.sendImage(h.file,false,{real:true});const messages=h.calls.filter(x=>x.message.method==='ui/message').map(x=>x.message.params.content);assert.equal(messages[0][1].data,'AQID');assert.equal(messages[0][1].mimeType,'image/png');assert.match(messages[0][0].text,/"status":"unsupported"/);assert.match(messages[0][0].text,/capture_health_record/);assert.equal(messages[0][0].text.match(/image-[a-f0-9]{64}/)[0],messages[1][0].text.match(/image-[a-f0-9]{64}/)[0]);assert.match(messages[0][0].text,/不得把檔案修改時間/);}finally{h.bridge.dispose();}});
test('real image read-only mode never authorizes writes',async()=>{const h=harness({message:{text:{},image:{}}},{real:true});try{await h.bridge.sendImage(h.file,false,{real:true,readOnly:true});const text=h.calls.find(x=>x.message.method==='ui/message').message.params.content[0].text;assert.match(text,/禁止任何寫入工具/);assert.doesNotMatch(text,/呼叫 capture_health_record/);}finally{h.bridge.dispose();}});
