'use client';
import {useEffect,useState,useCallback} from 'react';
import {Activity,ShieldCheck,Smartphone,ClipboardCheck,RefreshCw,Trash2,Download} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {kg,type Entry,type HealthInput} from '@/lib/health';
import {emptyEvidence} from '@/lib/date-evidence';
import {i18n,type Locale,type LocalePreference} from '@/lib/i18n';
import {useLocale} from '@/lib/use-locale';
import BatchPanel from './batch-panel';
type Draft=Entry&{status:string;issues:string[]};
type Data={namespace:'real'|'demo';realEnabled:boolean;records:Entry[];drafts:Draft[];total:number;nextOffset:number|null};
const blank:Data={namespace:'real',realEnabled:false,records:[],drafts:[],total:0,nextOffset:null};
const fresh=():HealthInput=>({kind:'body',date:null,timezone:'Asia/Taipei',unit:null,weight:null,bodyfat:null,exercise:null,load:null,reps:null,sets:null,notes:'',uncertain:[],dateEvidence:emptyEvidence()});
async function request(action?:string,args:Record<string,unknown>={}){const q=action?'':'?'+new URLSearchParams(Object.entries(args).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]));const r=await fetch('/api/health'+q,action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...args}),cache:'no-store'}:{cache:'no-store'});const j=await r.json() as Data & {error?:string;draft:Draft;issues:string[];deduplicated:boolean;deleted:boolean};if(!r.ok)throw new Error(j.error||'無法連線');return j;}
function Trend({points,unit,locale}:{points:{date:string,value:number}[];unit:string;locale:Locale}){
const t=(key:string)=>i18n.t(key,locale),n=(value:number)=>i18n.number(value,locale,1),d=(value:string,short=false)=>i18n.date(value,locale,short);
if(!points.length)return <div className="empty-chart">{t('儲存紀錄後，這裡會顯示趨勢')}</div>;
const values=points.map(p=>p.value),min=Math.floor(Math.min(...values)*.97*10)/10,max=Math.ceil(Math.max(...values)*1.03*10)/10;
const lo=Date.parse(points[0].date),hi=Date.parse(points.at(-1)!.date),x=(value:string)=>62+(hi===lo?.5:(Date.parse(value)-lo)/(hi-lo))*590,y=(v:number)=>205-(v-min)/(max-min||1)*170;
const path=points.map((p,i)=>`${i?'L':'M'}${x(p.date)},${y(p.value)}`).join(' ');
return <svg className="chart" viewBox="0 0 700 255" role="img" aria-label={i18n.t('chart.range',locale,{first:d(points[0].date),last:d(points.at(-1)!.date),unit})}><title>{points.map(p=>`${d(p.date)}: ${n(p.value)} ${unit}`).join('; ')}</title>{[0,.5,1].map(v=><g key={v}><line x1="62" x2="652" y1={205-v*170} y2={205-v*170} stroke="#e5eaf0"/><text x="49" y={210-v*170} textAnchor="end">{n(min+v*(max-min))}</text></g>)}<path d={`${path} L${x(points.at(-1)!.date)},205 L${x(points[0].date)},205 Z`} fill="#e8f1ff"/><path d={path} fill="none" stroke="#2266d7" strokeWidth="3"/>{points.map((p,i)=><circle key={i} cx={x(p.date)} cy={y(p.value)} r="4" fill="#2266d7"><title>{d(p.date)} · {n(p.value)} {unit}</title></circle>)}<text x="62" y="238">{d(points[0].date,true)}</text><text x="652" y="238" textAnchor="end">{d(points.at(-1)!.date,true)}</text><text x="62" y="20">{unit}</text></svg>;
}
const summary=(r:HealthInput&{namespace?:string},locale:Locale)=>r.kind==='body'?i18n.t('record.body',locale,{weight:i18n.number(r.weight,locale),unit:r.unit||i18n.t('單位待確認',locale),fat:r.bodyfat!==null?i18n.t('record.fat',locale,{value:i18n.number(r.bodyfat,locale)}):''}):i18n.t('record.strength',locale,{exercise:i18n.demoText(r.exercise,locale,r.namespace||'real'),load:i18n.number(r.load,locale),unit:r.unit||i18n.t('單位待確認',locale),reps:i18n.number(r.reps,locale),sets:i18n.number(r.sets,locale)});
export default function Dashboard(){
const {locale,preference,setPreference}=useLocale();
const t=(key:string,params:Record<string,unknown>={})=>i18n.t(key,locale,params),n=(value:number|null|undefined,digits?:number)=>i18n.number(value,locale,digits),d=(value:string|null|undefined)=>i18n.date(value,locale);

const [namespace,setNamespace]=useState<'real'|'demo'>('real'),[trash,setTrash]=useState(false),[data,setData]=useState<Data>(blank),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[install,setInstall]=useState(false),[input,setInput]=useState<HealthInput>(fresh),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID()),[source,setSource]=useState<string|null>(null),[review,setReview]=useState<{draft:Draft;issues:string[]}|null>(null),[exercise,setExercise]=useState(''),[deleting,setDeleting]=useState<{record:Entry;key:string}|null>(null);
const fetchRecords=useCallback(()=>request(undefined,{namespace,trash:trash?1:0}).then(next=>{setData(next);setError('');}).catch((e:Error)=>{setData({...blank,namespace});setError(e.message);}).finally(()=>setLoading(false)),[namespace,trash]);
const load=async()=>{setLoading(true);await fetchRecords();};
const switchView=(nextNamespace:'real'|'demo',nextTrash:boolean)=>{if(nextNamespace===namespace&&nextTrash===trash)return;setLoading(true);setNamespace(nextNamespace);setTrash(nextTrash);};
useEffect(()=>{void fetchRecords();},[fetchRecords]);useEffect(()=>{if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
const bodies=data.records.filter(r=>r.kind==='body'&&r.weight!==null).sort((a,b)=>a.date!.localeCompare(b.date!)),strength=data.records.filter(r=>r.kind==='strength'),exercises=Array.from(new Set(strength.map(r=>r.exercise!))),selected=strength.filter(r=>r.exercise===(exercises.includes(exercise)?exercise:exercises[0])).sort((a,b)=>a.date!.localeCompare(b.date!));
const first=bodies[0],last=bodies.at(-1),change=last&&first?kg(last.weight!,last.unit)-kg(first.weight!,first.unit):null;
const field=(k:keyof HealthInput,value:unknown)=>{setInput(s=>({...s,[k]:value,...(k==='date'||k==='timezone'?{dateEvidence:{...emptyEvidence(),...s.dateEvidence,userDate:null,userTimezone:null}}:{})}));setRequestKey(crypto.randomUUID());setReview(null);};
const edit=(draft?:Draft)=>{setInput(draft||fresh());setRequestKey(crypto.randomUUID());setSource(draft?.id||null);setReview(draft?{draft,issues:draft.issues}:null);setOpen(true);};
const confirmDate=()=>{setInput(s=>({...s,dateEvidence:{...emptyEvidence(),...s.dateEvidence,userDate:s.date,userTimezone:s.timezone}}));setReview(null);setRequestKey(crypto.randomUUID());};
return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-icon"><Activity size={24}/></span><div>{t('健康紀錄')}<small>{t('HEALTH LOG')}</small></div></div><div className="header-actions"><label className="locale-picker">{t('語言')} <select aria-label={t('語言')} title={t('自動：依瀏覽器語言；內嵌介面優先使用主程式提供的語言')} value={preference} onChange={e=>setPreference(e.target.value as LocalePreference)}><option value="auto">{t('自動')}</option><option value="zh-Hant">繁體中文</option><option value="en">English</option></select></label><span className="private"><ShieldCheck size={16}/>{t('僅限本人')}</span><button className="quiet" onClick={()=>setInstall(true)}><Smartphone size={18}/><span>{t('安裝到手機')}</span></button></div></header><main>
<div className="demo-banner"><span>{namespace==='demo'?t('合成測試資料'):t('我的健康紀錄')}</span>{namespace==='demo'?t('與正式紀錄完全分開，請只輸入合成數據'):t('由本人提供的照片或手動資料整理，原图不存入網站')}</div>
<div className="page-heading"><div><p className="eyebrow">{t('健康紀錄 v5')}</p><h1>{t('身體與訓練')}</h1><p className="muted">{t('清楚的照片數據自動記錄，日期與數字不明時等待釐清')}</p></div><div className="form-actions"><label>{t('資料空間')}<select aria-label={t('資料空間')} value={namespace} onChange={e=>switchView(e.target.value as 'real'|'demo',false)}><option value="real">{t('我的健康紀錄')}</option><option value="demo">{t('合成測試資料')}</option></select></label></div></div>
<BatchPanel locale={locale} namespace={namespace} trash={trash}/>
{error&&<div role="alert" className="error">{i18n.message(error,locale)} <button onClick={()=>void load()}>{t('重新載入')}</button></div>}{notice&&<p role="status" className="notice">{t(notice)}</p>}
<div className="record-toolbar"><button className={!trash?'primary':'secondary'} onClick={()=>switchView(namespace,false)}>{t('紀錄與趨勢')}</button><button className={trash?'primary':'secondary'} onClick={()=>switchView(namespace,true)}><Trash2 size={16}/>{t('回收區')}</button><a className="secondary" href="/api/health?export=1" download><Download size={16}/>{t('匯出我的資料')}</a></div>
{!trash&&<><div className="stats"><article><p>{t('最近體重')}</p><strong>{last?n(kg(last.weight!,last.unit),1):'—'}<span>kg</span></strong><small>{last?.date?d(last.date):t('尚無紀錄')}</small></article><article><p>{t('期間變化')}</p><strong>{change!==null?`${change>0?'+':''}${n(change,1)}`:'—'}<span>kg</span></strong><small>{t('weight.count',{count:n(bodies.length)})}</small></article><article><p>{t('訓練紀錄')}</p><strong>{n(strength.length)}<span>{t('筆')}</span></strong><small>{t('同一動作比較負重')}</small></article></div>
<div className="workspace"><section className="main-panel"><Tabs defaultValue="body"><div className="panel-heading"><TabsList className="metric-tabs"><TabsTrigger value="body">{t('體重趨勢')}</TabsTrigger><TabsTrigger value="strength">{t('重量訓練')}</TabsTrigger></TabsList><button className="icon-button" aria-label={t('重新載入紀錄')} onClick={()=>void load()}><RefreshCw size={17}/></button></div><TabsContent value="body"><div className="chart-heading"><div><h2>{t('每一次，留下軌跡')}</h2><p>{first&&last?`${d(first.date)} — ${d(last.date)}`:t('尚無紀錄')}</p></div><span className="legend">{t('體重 · kg')}</span></div><Trend locale={locale} points={bodies.map(r=>({date:r.date!,value:kg(r.weight!,r.unit)}))} unit="kg"/></TabsContent><TabsContent value="strength"><div className="chart-heading"><h2>{t('動作負重趨勢')}</h2><select aria-label={t('選擇訓練動作')} value={exercises.includes(exercise)?exercise:exercises[0]||''} onChange={e=>setExercise(e.target.value)}><option value="" disabled>{t('選擇動作')}</option>{exercises.map(v=><option key={v} value={v}>{i18n.demoText(v,locale,namespace)}</option>)}</select></div><Trend locale={locale} points={selected.map(r=>({date:r.date!,value:kg(r.load!,r.unit)}))} unit="kg"/></TabsContent></Tabs><div className="chart-foot">{t('只整理已入帳且未刪除的紀錄，不提供診斷或訓練處方')}{data.nextOffset!==null?t('。目前為部分紀錄，請載入更多。'):''}</div></section></div></>}
<section className="records-panel"><div className="section-title"><div><p className="eyebrow">{t(trash?'TRASH':'RECORDS')}</p><h2>{trash?t('回收區'):t('已入帳紀錄')} <span>{n(data.total)}</span></h2></div>{namespace==='demo'&&!trash&&<button className="secondary" disabled={busy} onClick={()=>void act(async()=>{await request('seed',{synthetic:true});await load();setNotice('合成示範資料已載入');})}>{t('載入示範資料')}</button>}</div>{trash&&<p className="muted" style={{padding:'0 24px 18px'}}>{t('刪除後不計入趨勢；可隨時還原。此處不提供永久清除。')}</p>}{loading?<p className="empty">{t('正在讀取私人紀錄…')}</p>:!data.records.length?<p className="empty">{trash?t('回收區沒有紀錄'):t('還沒有紀錄')}</p>:<Table><TableHeader><TableRow><TableHead>{t('日期')}</TableHead><TableHead>{t('項目')}</TableHead><TableHead>{t('紀錄')}</TableHead><TableHead>{t('備註／來源')}</TableHead><TableHead>{t('操作')}</TableHead></TableRow></TableHeader><TableBody>{[...data.records].sort((a,b)=>b.date!.localeCompare(a.date!)).map(r=><TableRow key={r.id}><TableCell>{d(r.date)}<small>{r.timezone}</small></TableCell><TableCell><span className={'record-kind '+r.kind}>{r.kind==='body'?t('體重'):i18n.demoText(r.exercise,locale,r.namespace)}</span></TableCell><TableCell>{summary(r,locale)}</TableCell><TableCell>{i18n.demoText(r.notes,locale,r.namespace)||'—'}{r.dateEvidence&&<small>{r.dateEvidence.userDate?t('本人確認日期'):r.dateEvidence.displayedDate?t('圖片顯示日期'):t('照片 EXIF 拍攝日期')}</small>}</TableCell><TableCell>{trash?<button className="secondary" disabled={busy} onClick={()=>void act(async()=>{await request('restore',{recordId:r.id,requestKey:crypto.randomUUID()});setNotice('紀錄已還原');await load();})}>{t('還原')}</button>:<button className="secondary" disabled={busy} onClick={()=>setDeleting({record:r,key:crypto.randomUUID()})}>{t('刪除')}</button>}</TableCell></TableRow>)}</TableBody></Table>}{data.nextOffset!==null&&<button className="secondary" disabled={busy} onClick={()=>void act(async()=>{const more=await request(undefined,{namespace,trash:trash?1:0,offset:data.nextOffset});setData({...more,records:[...data.records,...more.records]});})}>{t('載入更多')}</button>}</section>
{!trash&&data.drafts.length>0&&<section className="drafts-panel"><h2><ClipboardCheck size={20}/>{t('等待釐清')} ·{n(data.drafts.length)}</h2><p>{t('草稿不計入趨勢。請核對日期、時區和不確定欄位。')}</p>{data.drafts.map(d=><button className="draft-row" key={d.id} onClick={()=>edit(d)}><span>{d.date?i18n.date(d.date,locale):t('日期待確認')} · {summary(d,locale)}<small style={{display:'block'}}>{d.issues.map(issue=>i18n.message(issue,locale)).join(locale==='en'?'; ':'；')}</small></span><span>{t('核對內容')}</span></button>)}</section>}
<footer>{t('網頁與 ChatGPT 插件共用本人私人紀錄 · 需連線使用')}<br/>{t('照片只交由 ChatGPT 分析，網站保存結構化數據；不保存原圖或 GPS')}</footer></main>
<Dialog open={open} onOpenChange={setOpen}><DialogContent closeLabel={t('關閉')} className="entry-dialog"><DialogTitle>{t('review.title',{demo:namespace==='demo'?t('synthetic.prefix'):''})}</DialogTitle><DialogDescription>{t('填寫實際量測日期。修改後先更新草稿，再確認入帳。')}</DialogDescription><form onSubmit={e=>{e.preventDefault();void act(async()=>{const v=await request('draft',{namespace,synthetic:namespace==='demo',userProvided:namespace==='real',record:input,requestKey,replacesDraftId:source});setReview(v);setSource(v.draft.id);await load();});}}><div className="field-grid"><label>{t('紀錄類型')}<select value={input.kind} onChange={e=>field('kind',e.target.value)}><option value="body">{t('體重／體脂')}</option><option value="strength">{t('重量訓練')}</option></select></label><label>{t('量測日期')}<input type="date" value={input.date||''} onChange={e=>field('date',e.target.value||null)}/></label><label>{t('重量單位')}<select value={input.unit||''} onChange={e=>field('unit',e.target.value||null)}><option value="">{t('請確認單位')}</option><option value="kg">{t('kg 公斤')}</option><option value="lb">{t('lb 磅')}</option></select></label><label>{t('時區')}<input value={input.timezone} onChange={e=>field('timezone',e.target.value)}/></label>{(input.kind==='body'?[['weight',t('體重')],['bodyfat',t('體脂率 %（可留空）')]]:[['load',t('負重')],['reps',t('每組次數')],['sets',t('組數')]]).map(([k,label])=><label key={k}>{label}<input inputMode="decimal" type="number" step={k==='sets'||k==='reps'?'1':'0.1'} min="0" value={input[k as keyof HealthInput] as number??''} onChange={e=>field(k as keyof HealthInput,e.target.value===''?null:Number(e.target.value))}/></label>)}{input.kind==='strength'&&<label className="wide">{t('訓練動作')}<input value={input.exercise||''} onChange={e=>field('exercise',e.target.value)}/></label>}<label className="wide">{t('備註')}<input maxLength={500} value={input.notes} onChange={e=>field('notes',e.target.value)}/></label></div>
{namespace==='real'&&<div className="warning"><p>{t('photo.date',{value:input.dateEvidence?.exifDateTime||t('未提供 EXIF')})} {input.dateEvidence?.exifOffset||''}</p><p>{t('displayed.date',{value:input.dateEvidence?.displayedDate?d(input.dateEvidence.displayedDate):t('未提供')})}</p><button type="button" onClick={confirmDate} disabled={!input.date}>{t('我已核對上方量測日期與時區')}</button>{input.dateEvidence?.userDate&&<p>{t('confirmed.date',{date:d(input.dateEvidence.userDate),zone:input.dateEvidence.userTimezone})}</p>}</div>}
{input.uncertain.length>0&&<div className="warning">{t('uncertain.fields',{fields:input.uncertain.join(locale==='en'?', ':'、')})}<button type="button" onClick={()=>field('uncertain',[])}>{t('我已核對這些欄位')}</button></div>}{review&&<div className={review.issues.length?'warning':'review-ready'}>{review.issues.length?review.issues.map(issue=>i18n.message(issue,locale)).join(locale==='en'?'; ':'；'):t('草稿已建立，請再確認數值。')}</div>}{error&&<p role="alert" className="error">{i18n.message(error,locale)}</p>}<div className="form-actions"><button className="secondary" disabled={busy} type="submit">{source?t('更新草稿'):t('建立草稿')}</button>{review&&<button className="primary" type="button" disabled={busy||review.issues.length>0} onClick={()=>void act(async()=>{const result=await request('confirm',{draftId:review.draft.id,confirmed:true});setNotice(result.deleted?'相同紀錄在回收區，尚未恢復':result.deduplicated?'相同紀錄已存在，未重複新增':'紀錄已儲存');setOpen(false);await load();})}>{t('確認儲存')}</button>}</div></form></DialogContent></Dialog>
<Dialog open={!!deleting} onOpenChange={v=>{if(!v)setDeleting(null);}}><DialogContent closeLabel={t('關閉')}><DialogTitle>{t('刪除這筆紀錄？')}</DialogTitle><DialogDescription>{t('將移到回收區並從趨勢移除，可稍後還原。')}</DialogDescription>{deleting&&<p>{d(deleting.record.date)} · {summary(deleting.record,locale)}</p>}<div className="form-actions"><button className="secondary" onClick={()=>setDeleting(null)}>{t('取消')}</button><button className="primary" disabled={busy} onClick={()=>void act(async()=>{if(!deleting)return;await request('delete',{recordId:deleting.record.id,requestKey:deleting.key});setDeleting(null);setNotice('紀錄已移到回收區，可還原');await load();})}>{t('移到回收區')}</button></div></DialogContent></Dialog>
<Dialog open={install} onOpenChange={setInstall}><DialogContent closeLabel={t('關閉')}><DialogTitle>{t('安裝到手機')}</DialogTitle><DialogDescription>{t('以相同 ChatGPT 帳號登入這個私人網站。')}</DialogDescription><p>{t('iPhone／iPad：用 Safari 開啟網站，點分享，再選「加入主畫面」。')}</p><p>{t('Android：用 Chrome 開啟網站，在選單選「安裝應用程式」或「新增至主畫面」。')}</p><p className="muted">{t('需連網才能讀寫紀錄。安裝版不會在背景辨識照片，不快取健康資料。')}</p></DialogContent></Dialog></div>;
}
