export type DateEvidence={exifDateTime:string|null;exifOffset:string|null;displayedDate:string|null;displayedTimezone:string|null;userDate:string|null;userTimezone:string|null;captureRepresentsMeasurement:boolean;metadataStatus:string|null};
export const emptyEvidence=():DateEvidence=>({exifDateTime:null,exifOffset:null,displayedDate:null,displayedTimezone:null,userDate:null,userTimezone:null,captureRepresentsMeasurement:false,metadataStatus:null});
export function cleanEvidence(value:unknown):DateEvidence{const x=value&&typeof value==='object'?value as Record<string,unknown>:{};return Object.fromEntries(Object.keys(emptyEvidence()).map(k=>[k,k==='captureRepresentsMeasurement'?x[k]===true:typeof x[k]==='string'?(x[k] as string).trim().slice(0,80)||null:null])) as DateEvidence;}
export function validDate(v:string|null|undefined){return !!v&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;}
export function validOffset(v:string|null|undefined){if(!v||!/^[-+]\d{2}:\d{2}$/.test(v))return false;const h=Number(v.slice(1,3)),m=Number(v.slice(4));return h<=14&&m<60&&(h<14||m===0);}
export function validTimezone(v:string){if(/^UTC[-+]\d{2}:\d{2}$/.test(v))return validOffset(v.slice(3));try{new Intl.DateTimeFormat('en',{timeZone:v});return !!v;}catch{return false;}}
export function exifDate(v:string|null){if(!v||!/^\d{4}:\d{2}:\d{2} \d{2}:\d{2}:\d{2}$/.test(v))return null;const d=v.slice(0,10).replaceAll(':','-');return validDate(d)&&Number(v.slice(11,13))<24&&Number(v.slice(14,16))<60&&Number(v.slice(17,19))<60?d:null;}
function offsetAt(zone:string,stamp:string,offset:string){if(zone.startsWith('UTC')&&validOffset(zone.slice(3)))return zone.slice(3);try{const instant=stamp.slice(0,10).replaceAll(':','-')+'T'+stamp.slice(11)+offset;const parts=new Intl.DateTimeFormat('en',{timeZone:zone,timeZoneName:'longOffset'}).formatToParts(new Date(instant));const v=parts.find(p=>p.type==='timeZoneName')?.value;return v==='GMT'?'+00:00':v?.replace('GMT','');}catch{return undefined;}}
export function dateIssues(record:{date:string|null;timezone:string;dateEvidence?:DateEvidence}){const e=cleanEvidence(record.dateEvidence),out:string[]=[];const exif=exifDate(e.exifDateTime);if(e.userDate&&!validDate(e.userDate))out.push('本人提供的日期無效，請重新確認');if(!validDate(e.userDate)&&e.displayedDate&&!validDate(e.displayedDate))out.push('圖片日期格式不明，請核對');if(!validDate(e.userDate)&&e.exifDateTime&&!exif)out.push('EXIF 拍攝時間無效');if(!e.userTimezone&&e.exifOffset&&!validOffset(e.exifOffset))out.push('EXIF 時差無效');const user=validDate(e.userDate)?e.userDate:null,shown=validDate(e.displayedDate)?e.displayedDate:null;
if(!user&&exif&&shown&&exif!==shown)out.push('照片拍攝日期與畫面日期不同，請確認實際量測日期');
if(!user&&(e.metadataStatus==='invalid'||e.metadataStatus==='conflict'))out.push('照片中繼日期損壞或矛盾，請本人確認日期');
const selected=user||shown||(e.captureRepresentsMeasurement?exif:null);if(!selected)out.push('缺少可驗證的量測日期，請補充日期');else if(record.date!==selected)out.push('紀錄日期與日期來源不一致，請核對');
const zone=e.userTimezone||e.displayedTimezone;if(zone){if(!validTimezone(zone)||zone!==record.timezone)out.push('時區與提供的日期來源不一致');}else if(exif&&validOffset(e.exifOffset)){if(offsetAt(record.timezone,e.exifDateTime!,e.exifOffset!)!==e.exifOffset)out.push('時區與照片 EXIF 時差不一致');}else out.push('照片沒有可靠時區，請確認時區');
return out;}
