import {cleanEvidence,validTimezone,type DateEvidence} from './date-evidence';
export type HealthInput = {kind:'body'|'strength';date:string|null;timezone:string;unit:'kg'|'lb'|null;weight:number|null;bodyfat:number|null;exercise:string|null;load:number|null;reps:number|null;sets:number|null;notes:string;uncertain:string[];dateEvidence?:DateEvidence};
export type Entry = HealthInput & {id:string;created_at:string;namespace:'demo'|'real';deleted_at?:string|null;updated_at?:string|null};
export class AppError extends Error { constructor(public status:number,message:string){super(message);} }
export function requireOwner(headers:Headers){const id=headers.get('oai-authenticated-user-id');const email=headers.get('oai-authenticated-user-email');if(!id||!email)throw new AppError(401,'請先以 ChatGPT 登入');return id;}
export function cleanInput(input:unknown):HealthInput {const x=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;if(x.kind!=='body'&&x.kind!=='strength')throw new AppError(400,'請選擇體重或訓練紀錄');const num=(k:string)=>{if(x[k]===null||x[k]===undefined||x[k]==='')return null;if(typeof x[k]!=='number'||!Number.isFinite(x[k]))throw new AppError(400,`${k} 必須是數字`);return x[k] as number;};const text=(k:string,max:number)=>typeof x[k]==='string'?(x[k] as string).trim().slice(0,max):'';const date=text('date',100)||null;const unit=x.unit==='kg'||x.unit==='lb'?x.unit:null;const timezone=text('timezone',80)||'Asia/Taipei';if(!validTimezone(timezone))throw new AppError(400,'無效時區');return {kind:x.kind,date,timezone,unit,weight:x.kind==='body'?num('weight'):null,bodyfat:x.kind==='body'?num('bodyfat'):null,exercise:x.kind==='strength'?(text('exercise',100)||null):null,load:x.kind==='strength'?num('load'):null,reps:x.kind==='strength'?num('reps'):null,sets:x.kind==='strength'?num('sets'):null,notes:text('notes',500),uncertain:Array.isArray(x.uncertain)?x.uncertain.filter(v=>typeof v==='string').slice(0,12).map(v=>v.slice(0,100)):[],...(x.dateEvidence!==undefined?{dateEvidence:cleanEvidence(x.dateEvidence)}:{})};}
export function issues(x:HealthInput){const result:string[]=[];if(!x.date||!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||Number.isNaN(Date.parse(x.date+'T12:00:00Z'))||new Date(x.date+'T12:00:00Z').toISOString().slice(0,10)!==x.date)result.push('請確認實際紀錄日期');if(!x.unit)result.push('請確認重量單位');if(x.kind==='body'){if(x.weight===null||x.weight<=0||x.weight>1000)result.push('體重必須介於 0 與 1000 之間');if(x.bodyfat!==null&&(x.bodyfat<0||x.bodyfat>100))result.push('體脂率需介於 0 與 100%');}else{if(!x.exercise)result.push('請填寫動作名稱');if(x.load===null||x.load<0||x.load>2000)result.push('請確認訓練重量（可為 0）');if(x.reps===null||!Number.isInteger(x.reps)||x.reps<1||x.reps>1000)result.push('次數需為 1–1000 的整數');if(x.sets===null||!Number.isInteger(x.sets)||x.sets<1||x.sets>100)result.push('組數需為 1–100 的整數');}if(x.uncertain.length)result.push('請核對並清除不確定欄位：'+x.uncertain.join('、'));return result;}
export function kg(value:number,unit:string|null){return unit==='lb'?value*0.45359237:value;}
export async function fingerprint(x:HealthInput){const normalized={kind:x.kind,date:x.date,timezone:x.timezone,unit:x.unit,...(x.kind==='body'?{weight:x.weight,bodyfat:x.bodyfat}:{exercise:x.exercise?.trim().toLowerCase(),load:x.load,reps:x.reps,sets:x.sets}),notes:x.notes};const bytes=new TextEncoder().encode(JSON.stringify(normalized));return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');}
export const sampleInputs:HealthInput[] = Array.from({length:12},(_,i)=>({kind:'body',date:`2026-09-${String(3+i*2).padStart(2,'0')}`,timezone:'Asia/Taipei',unit:'kg',weight:Math.round((76.8-i*.11+Math.sin(i)*.16)*10)/10,bodyfat:Math.round((21.5-i*.06)*10)/10,exercise:null,load:null,reps:null,sets:null,notes:'合成示範資料',uncertain:[]} as HealthInput)).concat(Array.from({length:6},(_,i)=>({kind:'strength',date:`2026-09-${String(4+i*4).padStart(2,'0')}`,timezone:'Asia/Taipei',unit:'kg',weight:null,bodyfat:null,exercise:'深蹲',load:60+i*2.5,reps:8,sets:3,notes:'合成示範資料',uncertain:[]} as HealthInput)));
