import {env} from 'cloudflare:workers';
import {AppError,cleanInput,issues,fingerprint,sampleInputs,type HealthInput} from './health';
import {dateIssues} from './date-evidence';
export const CONSENT_VERSION='owner-photos-structured-v1';
type Namespace='demo'|'real';
export function db(){if(!env.DB)throw new AppError(503,'資料庫暫時無法使用，請稍後重試');return env.DB;}
export function realEnabled(owner:string){const e=env as unknown as Record<string,unknown>;return !!e.HEALTH_REAL_OWNER_ID&&owner===e.HEALTH_REAL_OWNER_ID&&e.HEALTH_REAL_CONSENT_VERSION===CONSENT_VERSION;}
export function scope(owner:string,value:unknown):Namespace{const ns=value===undefined?(realEnabled(owner)?'real':'demo'):value;if(ns!=='demo'&&ns!=='real')throw new AppError(400,'無效資料空間');if(ns==='real'&&!realEnabled(owner))throw new AppError(403,'此帳號尚未授權真實紀錄');return ns;}
type Row={id:string;payload:string;namespace:Namespace;status?:string;request_key?:string;created_at:string;deleted_at?:string|null;updated_at?:string|null};
function decode(row:Row){return {...JSON.parse(row.payload),id:row.id,namespace:row.namespace,created_at:row.created_at,...(row.status?{status:row.status}:{}),...(row.deleted_at!==undefined?{deleted_at:row.deleted_at,updated_at:row.updated_at}: {})};}
export function key(value:unknown){if(typeof value!=='string'||!value.trim()||value.length>160)throw new AppError(400,'需要穩定的請求編號');return value;}
function warnings(input:HealthInput,ns:Namespace){return [...issues(input),...(ns==='real'?dateIssues(input):[])];}
export async function listData(owner:string,args:Record<string,unknown>={}){const ns=scope(owner,args.namespace),trash=args.trash===true;const d=db();const offset=Number.isInteger(args.offset)&&Number(args.offset)>=0?Math.min(Number(args.offset),100000):0;const [r,p,c]=await Promise.all([d.prepare(`SELECT id,payload,namespace,created_at,deleted_at,updated_at FROM health_records WHERE owner_id=? AND namespace=? AND deleted_at IS ${trash?'NOT ':''}NULL ORDER BY created_at DESC LIMIT 500 OFFSET ?`).bind(owner,ns,offset).all<Row>(),d.prepare("SELECT id,payload,namespace,status,request_key,created_at FROM health_drafts WHERE owner_id=? AND namespace=? AND status='pending' ORDER BY created_at DESC LIMIT 100").bind(owner,ns).all<Row>(),d.prepare(`SELECT COUNT(*) AS count FROM health_records WHERE owner_id=? AND namespace=? AND deleted_at IS ${trash?'NOT ':''}NULL`).bind(owner,ns).first<{count:number}>()]);return {namespace:ns,syntheticOnly:ns==='demo',realEnabled:realEnabled(owner),consentVersion:realEnabled(owner)?CONSENT_VERSION:null,records:r.results.map(decode),drafts:trash?[]:p.results.map(row=>({...decode(row),issues:warnings(cleanInput(JSON.parse(row.payload)),ns)})),total:c?.count||0,offset,nextOffset:offset+r.results.length<(c?.count||0)?offset+r.results.length:null,trash};}
export async function createDraft(owner:string,args:Record<string,unknown>){
const ns=scope(owner,args.namespace);if(ns==='demo'&&args.synthetic!==true)throw new AppError(403,'示範空間只接受合成資料');if(ns==='real'&&args.userProvided!==true)throw new AppError(400,'只接受使用者本次提供的照片或手動紀錄');
const input=cleanInput(args.record),payload=JSON.stringify(input),requestKey=key(args.requestKey),d=db();
const existing=await d.prepare('SELECT id,payload,namespace,status,request_key,created_at FROM health_drafts WHERE owner_id=? AND namespace=? AND request_key=?').bind(owner,ns,requestKey).first<Row>();
if(existing){if(existing.payload!==payload)throw new AppError(409,'此請求編號已用於不同內容，請使用修正草稿流程');return {draft:decode(existing),issues:warnings(input,ns)};}
const replacing=typeof args.replacesDraftId==='string'?args.replacesDraftId:null;
if(replacing){const previous=await d.prepare("SELECT id FROM health_drafts WHERE owner_id=? AND namespace=? AND id=? AND status='pending'").bind(owner,ns,replacing).first();if(!previous)throw new AppError(409,'原草稿已變更，請重新載入後再編輯');}
const newId=crypto.randomUUID(),now=new Date().toISOString();const insert=replacing?d.prepare("INSERT OR IGNORE INTO health_drafts(id,owner_id,namespace,request_key,payload,status,created_at) SELECT ?,?,?,?,?,'pending',? WHERE EXISTS(SELECT 1 FROM health_drafts WHERE id=? AND owner_id=? AND namespace=? AND status='pending')").bind(newId,owner,ns,requestKey,payload,now,replacing,owner,ns):d.prepare("INSERT OR IGNORE INTO health_drafts(id,owner_id,namespace,request_key,payload,status,created_at) VALUES(?,?,?,?,?,'pending',?)").bind(newId,owner,ns,requestKey,payload,now);const statements=[insert];
if(replacing)statements.push(d.prepare("UPDATE health_drafts SET status='superseded' WHERE id=? AND owner_id=? AND namespace=? AND status='pending' AND EXISTS(SELECT 1 FROM health_drafts WHERE id=?)").bind(replacing,owner,ns,newId));await d.batch(statements);
const saved=await d.prepare('SELECT id,payload,namespace,status,request_key,created_at FROM health_drafts WHERE owner_id=? AND namespace=? AND request_key=?').bind(owner,ns,requestKey).first<Row>();if(!saved)throw new AppError(409,'原草稿已變更，請重新讀取');if(saved.payload!==payload)throw new AppError(409,'此請求編號已用於不同內容');return {draft:decode(saved!),issues:warnings(input,ns)};
}
async function persistDraft(owner:string,row:Row){const ns=scope(owner,row.namespace),input=cleanInput(JSON.parse(row.payload)),problems=warnings(input,ns);if(row.status!=='pending'&&row.status!=='confirmed')throw new AppError(409,'這筆草稿已被修正版本取代');if(problems.length)throw new AppError(422,problems.join('；'));
const hash=ns==='real'?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('source:'+row.request_key)))).map(v=>v.toString(16).padStart(2,'0')).join(''):await fingerprint(input),id=crypto.randomUUID(),now=new Date().toISOString(),d=db();
await d.batch([d.prepare("INSERT OR IGNORE INTO health_records(id,owner_id,namespace,fingerprint,payload,created_at,updated_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM health_drafts WHERE id=? AND owner_id=? AND namespace=? AND status IN ('pending','confirmed') AND payload=?)").bind(id,owner,ns,hash,JSON.stringify(input),now,now,row.id,owner,ns,row.payload),d.prepare("UPDATE health_drafts SET status='confirmed' WHERE id=? AND owner_id=? AND namespace=? AND status IN ('pending','confirmed') AND payload=?").bind(row.id,owner,ns,row.payload)]);
const saved=await d.prepare('SELECT id,payload,namespace,created_at,deleted_at,updated_at FROM health_records WHERE owner_id=? AND namespace=? AND fingerprint=?').bind(owner,ns,hash).first<Row>();if(!saved)throw new AppError(409,'草稿已被修正，請重新讀取');return {record:decode(saved),deduplicated:saved.id!==id,deleted:!!saved.deleted_at};}
export async function confirmDraft(owner:string,args:Record<string,unknown>){if(args.confirmed!==true)throw new AppError(400,'需要使用者確認這筆紀錄');const row=await db().prepare('SELECT id,payload,namespace,status,request_key,created_at FROM health_drafts WHERE owner_id=? AND id=?').bind(owner,String(args.draftId||'')).first<Row>();if(!row)throw new AppError(404,'找不到這筆草稿');return persistDraft(owner,row);}
export async function captureRecord(owner:string,args:Record<string,unknown>){if(args.namespace!=='real')throw new AppError(400,'自動記錄只適用個人正式空間');return {status:'pending',...await createDraft(owner,args)};}
export async function changeRecord(owner:string,args:Record<string,unknown>,action:'delete'|'restore'){const requestKey=key(args.requestKey),id=String(args.recordId||''),d=db();const row=await d.prepare('SELECT id,payload,namespace,created_at,deleted_at,updated_at FROM health_records WHERE owner_id=? AND id=?').bind(owner,id).first<Row>();if(!row)throw new AppError(404,'找不到這筆紀錄');scope(owner,row.namespace);
const old=await d.prepare('SELECT record_id,action FROM health_events WHERE owner_id=? AND request_key=?').bind(owner,requestKey).first<{record_id:string;action:string}>();if(old){if(old.record_id!==id||old.action!==action)throw new AppError(409,'請求編號已用於其他操作');return {record:decode(row),replayed:true};}
const now=new Date().toISOString(),eventId=crypto.randomUUID();await d.batch([d.prepare('INSERT OR IGNORE INTO health_events(id,owner_id,record_id,action,request_key,created_at) VALUES(?,?,?,?,?,?)').bind(eventId,owner,id,action,requestKey,now),d.prepare(`UPDATE health_records SET deleted_at=?,updated_at=? WHERE owner_id=? AND id=? AND deleted_at IS ${action==='delete'?'':'NOT '}NULL AND EXISTS(SELECT 1 FROM health_events WHERE id=? AND owner_id=? AND request_key=? AND record_id=? AND action=?)`).bind(action==='delete'?now:null,now,owner,id,eventId,owner,requestKey,id,action)]);
const recorded=await d.prepare('SELECT record_id,action FROM health_events WHERE owner_id=? AND request_key=?').bind(owner,requestKey).first<{record_id:string;action:string}>();if(recorded?.record_id!==id||recorded?.action!==action)throw new AppError(409,'請求編號已用於其他操作');const saved=await d.prepare('SELECT id,payload,namespace,created_at,deleted_at,updated_at FROM health_records WHERE owner_id=? AND id=?').bind(owner,id).first<Row>();return {record:decode(saved!),replayed:false};}
export async function seedDemo(owner:string){const d=db();await d.batch(await Promise.all(sampleInputs.map(async input=>d.prepare("INSERT OR IGNORE INTO health_records(id,owner_id,namespace,fingerprint,payload,created_at) VALUES(?,?,'demo',?,?,?)").bind(crypto.randomUUID(),owner,await fingerprint(input),JSON.stringify(input),new Date().toISOString()))));return listData(owner,{namespace:'demo'});}
export async function exportData(owner:string){const r=await db().prepare('SELECT id,payload,namespace,created_at,deleted_at,updated_at FROM health_records WHERE owner_id=? ORDER BY created_at DESC LIMIT 10001').bind(owner).all<Row>();if(r.results.length>10000)throw new AppError(413,'匯出超過 10000 筆，請聯絡支援分批匯出');const p=await db().prepare("SELECT id,payload,namespace,status,request_key,created_at FROM health_drafts WHERE owner_id=? AND status='pending' ORDER BY created_at DESC LIMIT 10001").bind(owner).all<Row>();if(p.results.length>10000)throw new AppError(413,'草稿超過匯出上限');return {formatVersion:1,exportedAt:new Date().toISOString(),records:r.results.map(decode),drafts:p.results.map(decode)};}
